### ISSUE TITLE
Sambamba mpileup using bed file has different results 

### ISSUE THREAD

**Issue by pjotrp** [lomereiter/sambamba#107]
Possibly related to samtools issue https://github.com/samtools/samtools/issues/282 

For now, be aware that mpileup with multiple threads may render slightly different results than the single 
core version (which uses no bed files).

**Comment by inijman** [comment]
With v0.5.1 mpileup with bed file segfaults.. I would appreciate a fix.

**Comment by pjotrp** [comment]
Can you give us a test setup that replicates the bug?
