### ISSUE TITLE
sambamba depth example

### ISSUE THREAD

**Issue by darked89** [lomereiter/sambamba#110]
I am having a problem finding out the proper usage of "sambamba  depth". I have tried to use it with 3 columns bed format but it reports  segmentation fault. The command was:
sambamba  depth  region --regions=test_head_cds.bed my_test.bam

Also, is it possible to calculate depth just at the specified single-base position on the chromosome? Like A in the starting ATG codon of CDS?

Many thanks.

Darek

**Comment by darked89** [comment]
Sorry for the late answer. 
I have used for testing:
http://code.google.com/p/gasv/downloads/detail?name=Example.bam

To be on the safe side I sorted it first, created 2 column bed with just few values:
<pre>
chr17   4353
chr17   43531
chr17   54353
chr17   64353
chr17   74353
</pre>

Run:
sambamba depth base -L foo_base.bed  Example.sorted.bam

got an error:
<pre>
REF	POS	COV	A	C	G	T	DEL	REFSKIP	SAMPLE
sambamba-depth: Conversion negative overflow
</pre>

Created another bed:
<pre>
chr17	4353	4453
chr17	43531	43631
chr17	54353	54453
chr17	64353	64453
chr17	74353	74453
</pre>

Run:
sambamba depth region -L foo_regions.bed -T 0  Example.sorted.bam
Got:
sambamba-depth: Conversion negative overflow

I am using Linux precompiled version with md5sum:
d21a9440f427cfb9bc542245361596fc sambamba

Hope this helps,

Darek

**Comment by lomereiter** [comment]
Thanks, the test case helped a lot.
Please try the latest version and see if you still run into any issues.

**Comment by darked89** [comment]
The version 0.5.1 seems to be working OK for me. Thanks a lot for fixing the problem in no time. One minor thing from the output:
<pre>
chr11	4520000	4530000	9063	87.5298	*
</pre>
The 87.5298 is CPM or RPKM?

Darek
PS For the stranded libraries it would be useful to have an option of reporting depth separately for plus and minus strand.

**Comment by lomereiter** [comment]
That column contains average coverage over the region. The tool wasn't designed with RNAseq in mind, so if you want to get RPKM, you should take that number divided by read length and library depth if I understand correctly.
