### ISSUE TITLE
sambamba view "*" SEQ string

### ISSUE THREAD

**Issue by cc2qe** [lomereiter/sambamba#112]
SAM spec allows the SEQ string (column 10) to be "*" when the sequence is not stored (http://samtools.github.io/hts-specs/SAMv1.pdf)
> SEQ: segment SEQuence. This field can be a ‘\*’ when the sequence is not stored. If not a ‘\*’,
the length of the sequence must equal the sum of lengths of M/I/S/=/X operations in CIGAR.
An ‘=’ denotes the base is identical to the reference base. No assumptions can be made on the
letter cases.

However, Sambamba view throws an error when trying to view such files (example: https://www.dropbox.com/s/sw8m8q16lcga8we/test.sam?dl=0)
```
sambamba view -S test.sam  | head
# sambamba-view: 1
```

Could Sambamba be modified to support "*" SEQ strings?

Thanks,
Colby

**Comment by lomereiter** [comment]
Such _sequences_ were always supported. In 0.5.1 a bug was fixed related to parsing SAM records with _QUAL_ set to `*` (weren't handled b/c of my oversight), and the latest version doesn't throw the error.

**Comment by cc2qe** [comment]
Ah, my apologies. I forgot that I was using sambamba 0.4.6. Thanks for the quick response, and great work on sambamba

--Colby
