### ISSUE TITLE
supplementary alignment filter in sambamba view

### ISSUE THREAD

**Issue by isthisthat** [lomereiter/sambamba#113]
Hello,
Could you add a filter for supplementary alignments in sambamba view? Some GATK/Picard programs have issues with those and I'd like to be able to filter those out. Thank you very much!
Stathis

**Comment by lomereiter** [comment]
Hi, I've uploaded the new binaries, flag `supplementary` is now supported.

**Comment by isthisthat** [comment]
works great! Thank you.
