### ISSUE TITLE
sambamba depth, region support for chr:start-end

### ISSUE THREAD

**Issue by isthisthat** [lomereiter/sambamba#114]
Hello,
It would be nice to be able to do the following for a quick and dirty depth calculation (not currently supported):

    sambamba depth region -L chr19 my.bam

As a workaround, I tried to do:

    sambamba depth region -L <(echo -e "chr19\t1\t59128983") my.bam

Which actually didn't output anything other than this (i.e. no depth was printed):

    Processing reference #20 (chr19)

But the following worked:

    echo -e "chr19\t1\t59128983" > chr19.bed
    sambamba depth region -L chr19.bed my.bam

Thanks,
Stathis

**Comment by lomereiter** [comment]
Hi Stathis,

I finally got around to polishing `depth` tool, so it now supports `-L chr19` and `-L chr19:1-59128983`.
However, there is no special treatment for the simple cases you describe, so it's quite a bit slower than simple read counting. Compare:
```
$ time sambamba depth region ~/Downloads/test.bam -L 1
# chrom	chromStart	chromEnd	readCount	meanCoverage	sampleName
Processing reference #1 (1)
1	0	249250621	74376	0.0439668	CPCT02030056R	

real	0m4.381s
user	0m3.983s
sys	0m0.033s
$ time sambamba view -c ~/Downloads/test.bam 1 -F "not unmapped and not duplicate and mapping_quality > 0"
74376

real	0m0.195s
user	0m0.200s
sys	0m0.077s
```

**Comment by isthisthat** [comment]
Thanks Artem! I'll test that in the next release.
Stathis
