### ISSUE TITLE
A memory leak in sort

### ISSUE THREAD

**Issue by goranrakocevic** [lomereiter/sambamba#116]
I'm using 0.5.0-alpha to sort a large (100 GB) BAM file (BWA-MEM | Samblaster | Sambamba view | Sambamba sort). 

There appears to be a fairly slow but steady memory leak in the sort tool. I'm running it with  -t 32 -l 5 -m 28 GiB, several hours into the process I see that sort has climbed to 36.9G. (View is started with -l 0 if that is of any consequence).

**Comment by lomereiter** [comment]
I eliminated a leak (didn't do much testing, though) in the commit https://github.com/biod/BioD/commit/5d94926633ebf8b55edb90f7e3bbe0549218b0cb
The updated binary, that can be tested, is here - https://dl.dropboxusercontent.com/u/7916095/sambamba_31_01_2015

**Comment by goranrakocevic** [comment]
Thanks for the fast response, I'll do a couple of test-runs and report back.

**Comment by goranrakocevic** [comment]
Unfortunately, looks like there is still an issue. Seems like it's a little slower (I may be imagining it though), but about 2 hours into the same process described above, sort is taking 35GB of RAM

**Comment by lomereiter** [comment]
Thanks, I'll run it under Valgrind then.

**Comment by lomereiter** [comment]
Now I did a bit of testing on a 7GB file, and the tool seems to respect the memory limit (I also checked that 2 commits back it didn't).
The latest build is at https://dl.dropboxusercontent.com/u/7916095/sambamba_02_02_2015

**Comment by asimenos** [comment]
Artem,

You may want to make a new sambamba release from the latest sources, just to ensure that people have access to this fix. The current published binary (0.5.1) suffers from the memory leak, and in quite a few scenarios (exomes, whole genomes, sorting, merging) it runs out of memory on AWS instances. I've rebuilt the latest version from source and it fixes the bug. But given that Ubuntu 14 doesn't come with a package for ldc, it may not be trivial for others.

Thanks again for making sambamba.

**Comment by lomereiter** [comment]
@asimenos thanks for the remainder, I've uploaded new binaries

**Comment by crazyhottommy** [comment]
I am using sambamba v0.5.4. I am sorting a file of 130G.

After 1 hours running the program, the mem usage has climbed to 70G!

```
top - 22:14:36 up 274 days, 10:57,  1 user,  load average: 9.63, 9.89, 9.97
Tasks: 600 total,   2 running, 597 sleeping,   0 stopped,   1 zombie
Cpu(s):  4.2%us,  0.2%sy,  0.0%ni, 95.6%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   189.033G total,   83.980G used,  105.053G free,  212.379M buffers
Swap:   31.625G total,   69.000M used,   31.558G free, 5845.824M cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                   
 6673 mtang1    20   0  147g  64g 1444 S  0.0 34.1   1:18.89 sambamba                                                     6612 mtang1    20   0 7573m 5.9g 1064 S  3.7  3.1 753:22.71 bwa                                                          6614 mtang1    20   0 1980m 1.9g  944 S  0.0  1.0   3:54.20 samblaster                                                 
 6585 root       0 -20 13.4g 1.2g 107m S  0.3  0.6   3007:19 mmfsd                                                        6609 mtang1    20   0 1054m 1.0g  768 S  4.3  0.5   1:48.08 mbuffer                                                      6608 mtang1    20   0 1031m 849m 4632 R 99.9  0.4  67:50.97 python2.7                                                  
 6682 mtang1    20   0 1231m 214m 1444 S  0.0  0.1   0:00.40 sambamba                                                     6679 mtang1    20   0 1195m  67m 1444 S  0.0  0.0   0:00.11 sambamba                                                     6615 mtang1    20   0 1841m  62m 1416 S  0.0  0.0   8:31.62 sambamba                                                   
 6678 mtang1    20   0 1841m  61m 1416 S  0.0  0.0   0:00.60 sambamba                                                     6681 mtang1    20   0 1841m  59m 1416 S  0.0  0.0   0:02.11 sambamba  
```

Is the mem leakage still a problem here?
Thanks,
Ming
