### ISSUE TITLE
sort tmp files closed before removing?

### ISSUE THREAD

**Issue by goranrakocevic** [lomereiter/sambamba#124]
Hi,

I've tried running sort in a NFS mounted directory (tmp is also in this directory). I sort exists with the error:
sambamba-sort: Failed to remove file ./sambamba-pid30-osbs/.nfs00000000008a005200000003: Device or resource busy

This tends to happen if a process maintains an open handle on a file that is removed. Removing the directory then fails.
Not placing the tmp on the nfs is a way around the issue, but it would be helpful if it could work this way as well.

**Comment by lomereiter** [comment]
Fixed by Brad.

**Comment by cc2qe** [comment]
thanks for this fix! I was having this problem as well and had no idea how to address it
