### ISSUE TITLE
allow samtools path/version in pileup

### ISSUE THREAD

**Issue by inijman** [lomereiter/sambamba#125]
Since the change in samtools from 0.x to 1.x has a fundamental change in the way pileups are made (ie with or without overlapping reads in PE data) it would be nice to not only take the samtools in $PATH but to allow a specific version.

**Comment by lomereiter** [comment]
Ies, is it fine to drop support for samtools 0.x already?

**Comment by inijman** [comment]
HI Artem,

I could see some people complaining about this, since there is a major change in the way how overlapping reads from a paired set are handled between samtools 0.x and 1. IN the latter, the overlapping bit is counted single and in samtools 0.x it is double. I think to could the overlapping bit only once makes much more sense, but it does create significant differences in your output (and a visual discrepancy with IGV…).

If people want continuity in there project and do not want to rerun everything they will have a problem.

We did implement sambamba pileup in our pipelines yet, since we keep having troubles with it, but if we would do, we would go with samtools 1.1.

Best,
Ies

Van: Artem Tarasov [mailto:notifications@github.com]
Verzonden: zaterdag 11 april 2015 17:06
Aan: lomereiter/sambamba
CC: Nijman, I.J.
Onderwerp: Re: [sambamba] allow samtools path/version in pileup (#125)


Ies, is it fine to drop support for samtools 0.x already?

—
Reply to this email directly or view it on GitHub<https://github.com/lomereiter/sambamba/issues/125#issuecomment-91868410>.

------------------------------------------------------------------------------

De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is
uitsluitend bestemd voor de geadresseerde. Indien u dit bericht onterecht
ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct
te informeren door het bericht te retourneren. Het Universitair Medisch
Centrum Utrecht is een publiekrechtelijke rechtspersoon in de zin van de W.H.W.
(Wet Hoger Onderwijs en Wetenschappelijk Onderzoek) en staat geregistreerd bij
de Kamer van Koophandel voor Midden-Nederland onder nr. 30244197.

Denk s.v.p aan het milieu voor u deze e-mail afdrukt.

------------------------------------------------------------------------------

This message may contain confidential information and is intended exclusively
for the addressee. If you receive this message unintentionally, please do not
use the contents but notify the sender immediately by return e-mail. University
Medical Center Utrecht is a legal person by public law and is registered at
the Chamber of Commerce for Midden-Nederland under no. 30244197.

Please consider the environment before printing this e-mail.

**Comment by lomereiter** [comment]
I've just committed a large update to the pileup command, it should fix the issues (I could reproduce them). Currently only 1.x versions are supported, supporing for 0.x just requires more boilerplate, and I will add it eventually.

**Comment by inijman** [comment]
Ok cool; we'll give it a try!

Thanks, ies

Verstuurd vanaf mijn iPhone

Op 11 apr. 2015 om 17:20 heeft Artem Tarasov <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I've just committed a large update to the pileup command, it should fix the issues (I could reproduce them). Currently only 1.x versions are supported, supporing for 0.x just requires more boilerplate, and I will add it eventually.

—
Reply to this email directly or view it on GitHub<https://github.com/lomereiter/sambamba/issues/125#issuecomment-91869035>.

------------------------------------------------------------------------------

De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is
uitsluitend bestemd voor de geadresseerde. Indien u dit bericht onterecht
ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct
te informeren door het bericht te retourneren. Het Universitair Medisch
Centrum Utrecht is een publiekrechtelijke rechtspersoon in de zin van de W.H.W.
(Wet Hoger Onderwijs en Wetenschappelijk Onderzoek) en staat geregistreerd bij
de Kamer van Koophandel voor Midden-Nederland onder nr. 30244197.

Denk s.v.p aan het milieu voor u deze e-mail afdrukt.

------------------------------------------------------------------------------

This message may contain confidential information and is intended exclusively
for the addressee. If you receive this message unintentionally, please do not
use the contents but notify the sender immediately by return e-mail. University
Medical Center Utrecht is a legal person by public law and is registered at
the Chamber of Commerce for Midden-Nederland under no. 30244197.

Please consider the environment before printing this e-mail.

**Comment by inijman** [comment]
Is this going to be 0.5.3? Will you build the binary as well?

Ies

Van: Artem Tarasov [mailto:notifications@github.com]
Verzonden: zaterdag 11 april 2015 17:20
Aan: lomereiter/sambamba
CC: Nijman, I.J.
Onderwerp: Re: [sambamba] allow samtools path/version in pileup (#125)


I've just committed a large update to the pileup command, it should fix the issues (I could reproduce them). Currently only 1.x versions are supported, supporing for 0.x just requires more boilerplate, and I will add it eventually.

—
Reply to this email directly or view it on GitHub<https://github.com/lomereiter/sambamba/issues/125#issuecomment-91869035>.

------------------------------------------------------------------------------

De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is
uitsluitend bestemd voor de geadresseerde. Indien u dit bericht onterecht
ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct
te informeren door het bericht te retourneren. Het Universitair Medisch
Centrum Utrecht is een publiekrechtelijke rechtspersoon in de zin van de W.H.W.
(Wet Hoger Onderwijs en Wetenschappelijk Onderzoek) en staat geregistreerd bij
de Kamer van Koophandel voor Midden-Nederland onder nr. 30244197.

Denk s.v.p aan het milieu voor u deze e-mail afdrukt.

------------------------------------------------------------------------------

This message may contain confidential information and is intended exclusively
for the addressee. If you receive this message unintentionally, please do not
use the contents but notify the sender immediately by return e-mail. University
Medical Center Utrecht is a legal person by public law and is registered at
the Chamber of Commerce for Midden-Nederland under no. 30244197.

Please consider the environment before printing this e-mail.

**Comment by lomereiter** [comment]
Yes, I will do a little more testing and then a new release. Until then, here's a [link](https://dl.dropboxusercontent.com/u/7916095/sambamba_11_04_2015) to the built binary.
