### ISSUE TITLE
markdup read choice

### ISSUE THREAD

**Issue by lonestar21** [lomereiter/sambamba#126]
Hi Artem,
I'm comparing the results from dup marking with Picard against dupmarking results with sambamba.   I see in your paper that you use the same criteria for dup marking as Picard.

When I compare the results I'm noticing that the results are extremely similar, but not identical.   The total counts of duplicates is the same, but, interestingly, there are occasionally different choices for which reads in a set of duplicates are marked as a duplicate.   Have you seen this before?  Do you know of any reasons that the results would be different?

Picard version: picard-tools-1.122
Sambamba version: sambamba_02_02_2015

**Comment by lomereiter** [comment]
Yes, I've seen this, it happens when the scores are identical for two or more (paired-end) reads, and as far as I remember Picard doesn't use stable sort, so the results are not completely the same but equivalent in this sense.
