### ISSUE TITLE
Cannot open or create file '/dev/stdout' on mac using markdup

### ISSUE THREAD

**Issue by bwlang** [lomereiter/sambamba#129]
sambamba markdup ACGAATCC_L001_R1_001.bam /dev/stdout | sambamba view /dev/stdin
finding positions of the duplicate reads in the file...
  sorting 0 end pairs...   done in 0 ms
  sorting 657345 single ends (among them 0 unmatched pairs)... done in 14 ms
  collecting virtual offsets of duplicate reads...   done in 7 ms
  found 2896 duplicates, sorting the list...   done in 0 ms
collected list of positions in 0 min 0 sec
sambamba-markdup: Cannot open or create file '/dev/stdout'
sambamba-view: not enough data in stream

I can do it with a named pipe...
e.g. 
mkfifo nodup
sambamba markdup ACGAATCC_L001_R1_001.bam nodups && sambamba view nodups

sambamba markdup ACGAATCC_L001_R1_001.bam /dev/stdout | sambamba view /dev/stdin 
does work on a linux host

**Comment by pjotrp** [comment]
Inactive
