### ISSUE TITLE
best options for a markdups on a huge RAM machine?

### ISSUE THREAD

**Issue by RichardCorbett** [lomereiter/sambamba#131]
Hi.
I have a machine with almost 800Gigs of RAM.  I also have a 200X super-deep genome bam needing duplicate marking.   What set of parameters would you recommend to get the best (fastest) markdups results?

If there are other tools better suited, I'd be happy to hear about those too.

thanks,
Richard

**Comment by lomereiter** [comment]
Hi,
you should increase `--hash-table-size` and `--overflow-list-size` up to some 1-10 million.

Among other tools, you can try `biobambam` (markduplicates2); if the file happens to be name-sorted, use `samblaster`

**Comment by isthisthat** [comment]
Hi Artem, wordeing if you've done any benchmarking against markduplicates2? Is it as fast as sambamba?

**Comment by lomereiter** [comment]
@isthisthat No, I haven't. But judging by its code, I think it should be as fast.
