### ISSUE TITLE
Sambamba does not seem to follow a 'natural' (mixed sort) order when name-sorting, thus breaking compatibility with samtools

### ISSUE THREAD

**Issue by schelhorn** [lomereiter/sambamba#132]
I appeared to me that sambamba does seem to apply a lexicographic ordering rather then a natural (aka mixed sort) ordering when sorting for query names. This is in contrast to samtools, which [applies mixed sort ordering](http://sourceforge.net/p/samtools/mailman/message/25715432/) (i.e., it parses the query name into strings and integers and sorts based on that). These two strategies produce significantly different orderings. 

Is this behaviour of sambamba on purpose? It somewhat complicates comparability of results between sambamba and the _de-facto_ standard samtools. Other projects may expect (maybe unjustified so) sambamba to be a drop-in replacement for samtools, as for example [bcbio](https://github.com/chapmanb/bcbio-nextgen). 

If sambamba's behaviour is different in such core aspects then I suggest that this should be clearly stated in the documentation in order to avoid misunderstandings. Even better, of course, an option for natural-sort ordering could be implemented.

**Comment by lomereiter** [comment]
The major use of sorting by name is making so that paired reads one after another, but I imagine that a mix of `sambamba sort -n` and `samtools merge` may fail.

Closing this issue as a duplicate, please subscribe to https://github.com/lomereiter/sambamba/issues/109
