### ISSUE TITLE
Add sambamba to GNU Guix

### ISSUE THREAD

**Issue by pjotrp** [lomereiter/sambamba#133]
GNU Guix is a next generation packaging system. Recently it got llvm support, so we should add ldc and sambamba as packages with dependencies. On my list of things to do!

**Comment by pjotrp** [comment]
Done. Needs to go on mainline master soon.

**Comment by rekado** [comment]
See also https://github.com/BIMSBbioinfo/guix-bimsb/blob/master/bimsb/packages/staging.scm#L2083

**Comment by pjotrp** [comment]
Cool. This is mine - : https://github.com/genenetwork/guix-bioinformatics/blob/master/gn/packages/sambamba.scm. Later version includes test target and undeaD updates. I'll warn you when we do a next release (soon).
