### ISSUE TITLE
Issue with OSX prebuilt binary execution

### ISSUE THREAD

**Issue by buckaroobonzai** [lomereiter/sambamba#135]
I installed the prebuilt binary on a machine running OSX Yosemite and added the sambamba executable to my path. The sambamba view command does not execute.  However ./sambamba_v0.5.4 view does execute (see below), but only when in the sambamba directory.

-rwxr-xr-x@   1 hiten  staff   7.7M Apr 14 14:04 sambamba_v0.5.4
drwxr-xr-x@ 112 hiten  staff   3.7K Feb 16 17:49 samtools-1.2
drwxr-xr-x   17 hiten  staff   578B Mar 27 15:10 seriesoftubes
drwxr-xr-x    3 root   staff   102B Feb 16 17:51 share
drwxr-xr-x@   9 hiten  staff   306B Apr 10 16:06 sratoolkit.2.4.5-2-mac64
drwxr-xr-x@  25 hiten  staff   850B Feb 27 08:27 tophat-2.0.13.OSX_x86_64
(12:21 hiten@serendipity ~) > sambamba view
-bash: sambamba: command not found
(12:21 hiten@serendipity ~) > sambamba_v0.5.4 view
-bash: sambamba_v0.5.4: command not found
(12:22 hiten@serendipity ~) > ./sambamba_v0.5.4 view
Usage: sambamba-view [options] <input.bam | input.sam> [region1 [...]]

Options: -F, --filter=FILTER
                    set custom filter for alignments
         -f, --format=sam|bam|cram|json
                    specify which format to use for output (default is SAM)
         -h, --with-header
                    print header before reads (always done for BAM output)
         -H, --header
                    output only header to stdout (if format=bam, the header is printed as SAM)
         -I, --reference-info
                    output to stdout only reference names and lengths in JSON
         -L, --regions=FILENAME
                    output only reads overlapping one of regions from the BED file
         -c, --count
                    output to stdout only count of matching records, hHI are ignored
         -v, --valid
                    output only valid alignments
         -S, --sam-input
                    specify that input is in SAM format
         -C, --cram-input
                    specify that input is in CRAM format
         -T, --ref-filename=FASTA
                    specify reference for writing CRAM
         -p, --show-progress
                    show progressbar in STDERR (works only for BAM files with no regions specified)
         -l, --compression-level
                    specify compression level (from 0 to 9, works only for BAM output)
         -o, --output-filename
                    specify output filename
         -t, --nthreads=NTHREADS
                    maximum number of threads to use
         -s, --subsample=FRACTION
                    subsample reads (read pairs)
         --subsampling-seed=SEED
                    set seed for subsampling

**Comment by lomereiter** [comment]
Have you added the *executable* name to the $PATH or the *directory* it's located in? It should be the latter. For convenience, you can rename the executable, but I'd suggest to make a symbolic link to it (`ln -s`)

**Comment by buckaroobonzai** [comment]
That was the problem.  Added the symbolic link and so now I can do the
head-to-head comparison with samtools!

On Wed, Apr 15, 2015 at 12:39 PM, Artem Tarasov <notifications@github.com>
wrote:

> Have you added the *executable* name to the $PATH or the *directory* it's
> located in? It should be the latter. For convenience, you can rename the
> executable, but I'd suggest to make a symbolic link to it (ln -s)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lomereiter/sambamba/issues/135#issuecomment-93543163>.
>



-- 
Hiten Madhani
​​

Biochemistry and Biophysics
UCSF
600 16th St., Rm. N372C
San Francisco, CA 94158-2200
http://madhanilab.ucsf.edu
