### ISSUE TITLE
markdup not applied to supplementary alignments

### ISSUE THREAD

**Issue by roryk** [lomereiter/sambamba#136]
Hi Artem,

I'm not sure if this is a bug or by design-- markdup doesn't  propagate the duplicate tag to supplementary alignments. I have an example file where the primary alignments are marked but the supplementary alignments for the same read are not. Is that intended?

Thanks!

**Comment by lomereiter** [comment]
Hi,

I'd say it's by design. Propagating to secondary/supplementary alignments would require too much bookkeeping memory-wise (a hash table keeping lists of appearances for each read name).

**Comment by roryk** [comment]
Thanks for the answer Artem.
