### ISSUE TITLE
SAM to uncompressed BAM with ~3000 contigs

### ISSUE THREAD

**Issue by cc2qe** [lomereiter/sambamba#137]
On a SAM file with ~3000 contigs, Sambamba has problems converting a SAM file to uncompressed BAM. I've made a small example: http://colbychiang.com/hall/tmp/b.sam

```bash
$ sambamba_v0.5.4 view -S -f bam -l 0 b.sam  > b.bam
sambamba-view: [zlib] unknown error
```

Thanks,
Colby

**Comment by lomereiter** [comment]
Thanks for the testcase. Indeed the compression buffer size was incorrectly specified.
