### ISSUE TITLE
Sambamba index, incosistent command line usage and documentation

### ISSUE THREAD

**Issue by rernst** [lomereiter/sambamba#138]
The documentation (github.io) states that sambamba index can be used as follows: sambamba index <input.bam> <output.bai>. Where we the output.bai file is optional. This seems to be changed somewhere between 0.4.7 and 0.5.4, as currently it is not possible to to give an output.bai: "sambamba-index <input.bam>". 

Is this a bug or inconsistent documentation? I can't find the change in the release notes, I would expect it to be in there as this is changing the behaviour of sambamba index (our pipeline crashed).

**Comment by lomereiter** [comment]
That's inconsistent documentation.
I have added the change in release notes to v0.5.0. The documentation on the website is still a bit outdated, I'll keep this issue open until I find time to update the docs.

Is there any real need for an index file to have a non-default filename? If there is, I'd add that behaviour back.

**Comment by rernst** [comment]
Okay, I believe there are some tools that need a file.bai instead of a file.bam.bai but I am not 100% sure. @inijman do you know? Otherwise, I'll try to figure this out next week.

**Comment by pjotrp** [comment]
One thing that comes up is that output files may need to be written in different directories. The samtools assumption that the index should be in the same directory forces people to 
copy files or symlink them adding unnecessary complexity in scripting. Allowing a different output name/path is generally a good idea.

**Comment by rernst** [comment]
I agree with @pjotrp. I also asked Ies and he says there are indeed some tools that need a "sample.bai". For example, freebayes.

**Comment by rernst** [comment]
Thanks for the commit!
