### ISSUE TITLE
Sambamba view downsampling safe?

### ISSUE THREAD

**Issue by isthisthat** [lomereiter/sambamba#139]
Hi Artem,
This recently came up in a discussion around the "safety" of downsampling and the possible introduction of biases. I assume when downsampling, you either keep or throw a read pair (i.e., you wouldn't throw one read in a pair) and that there is no distinction between aligned and unaligned reads (i.e., they are discarded with the same probability). Finally, when throwing a read-pair away, do you also discard any secondary or supplementary alignments it may have?
Thanks for your support!
Stathis

**Comment by lomereiter** [comment]
Hi Stathis,
Yes, all your assumptions are correct. All alignments sharing the same read name are treated similarly.
(If you are interested, technical implementation is as follows, borrowed from samtools: a hash of read name is taken, and under the assumption of its uniformity reads are discarded whenever it exceeds the threshold.)

**Comment by isthisthat** [comment]
Thanks Artem. That's very helpful.

**Comment by isthisthat** [comment]
Last question: would it be feasible to mark duplicates at the time of downsampling? That would save a whole lot of processing time and memory. I imagine this may be possible given a coordinate-sorted bam. Thanks a lot!

**Comment by lomereiter** [comment]
Yes, it's definitely possible, I'll add that as a new issue.
