### ISSUE TITLE
markdup downsampling option

### ISSUE THREAD

**Issue by lomereiter** [lomereiter/sambamba#140]

**Comment by isthisthat** [comment]
Hi Artem, any chance for this and external sort in markdup in future releases?
Thanks a lot, Stathis

**Comment by lomereiter** [comment]
Hi Stathis,

External sort is on my list, I'll definitely work on it very soon.

I'm not so sure about the downsampling. Let me clarify: you want it to be applied to the `markdup` output, or the other way around? Basically, there are two options:
1. Run markdup and then downsample. This requires reading the (large) input file twice and writing (smaller) output once (using a pipe `markdup | view`). And I don't see how that can be improved.
2. Run downsample and then markdup. Then the (large) input is read only once, but there are two (smaller) outputs, before and after markdup. Here, a single reading of the first output can be saved (by computing duplicate offsets while writing), but given that the compression (even at the lowest level) is about 3x slower than decompression, that's not much of an improvement.
From my calculations, the second way is faster only when the rate is less than 0.2, and then I can only speed it up by ~8%, which is significant, but not that much. Maybe there's a more tricky approach that I overlook, but that's how I see it.

**Comment by isthisthat** [comment]
Hi Artem,
I was looking for 2. Basically dowsample+markdup in one go, or a "duplicate aware" downsample. In a sense these two operations should always go together since a not properly dup-marked bam can lead to erroneous calculations downstream.
Can you not resolve duplicates at the time of downsampling if a bam is coordinate-sorted? (eliminating the need for the two outputs you mention).

**Comment by lomereiter** [comment]
I understand what you want, but I have no idea if it can be implemented more efficiently. The problem here is more or less the same as with your other suggestion (#115), thatis, the mate read must be found for each read, which in principle can be arbitrarily far away in the file. In fact, none of the tools I know—even the so-called 'streaming' `biobambam`, on the algorithm whereof `markdup` is based—avoids traversing input file contents twice. Only Samblaster avoids the need for two passes, but it does so by requiring input to be name-sorted and always retaining only the first pair in each set of duplicates (instead of the best one, claiming the impact of it negligible).
