### ISSUE TITLE
Sambamba index produces corrupted indices when used with standard input

### ISSUE THREAD

**Issue by asimenos** [lomereiter/sambamba#144]
It appears that `sambamba index` will produce different results if given a filename directly, versus the same file via stdin. In the following example, I am using the latest build (but the same happens with 0.5.4):

```
$ ls -la
total 76726064
drwxrwsr-x 1 dnanexus 1002          32 Jun  9 23:17 .
drwxrwsr-x 1 dnanexus 1002         378 Jun  9 23:13 ..
-rw-rw-r-- 2 dnanexus 1002 78561183962 Jun  9 20:58 file.bam
-rwxrwxr-x 1 dnanexus 1002     6303314 Jun  9 23:17 sambamba
$ cat file.bam | ./sambamba index -c -t 32 /dev/stdin problematic-file.bam.bai                                                                                                               
$ ./sambamba index -c -t 32 file.bam
$ ls -l
total 76741048
-rw-rw-r-- 2 dnanexus 1002 78561183962 Jun  9 20:58 file.bam
-rw-rw-r-- 1 dnanexus 1002     8939160 Jun  9 23:31 file.bam.bai
-rw-rw-r-- 1 dnanexus 1002     6399688 Jun  9 23:22 problematic-file.bam.bai
-rwxrwxr-x 1 dnanexus 1002     6303314 Jun  9 23:17 sambamba
```

The index produced via the "streaming" execution is always smaller in size, as in the example above. That problematic index seems corrupted, because subsequent sambamba invocations which would use it (such as "sambamba view") end up segfaulting.

I've tried on both a whole genome and a whole exome bam, and the behavior is the same. So I suspect you'll be able to reproduce it on any bam; let me know if not and I can send you a link to one of these bams (they are straight out of BWA, so nothing weird).

Side-note: the original use case is for indexing the result of "samtools cat". I am doing per-chromosome processing, and end up with multiple bams which need to be concatenated (without transcoding). "Samtools cat" does exactly that, but does not produce an index, so I am piping its results to "sambamba index" (via "tee") in order to index the file in real time. If you could add "sambamba cat" functionality to sambamba, that would be great :-)

**Comment by lomereiter** [comment]
Thanks for the report. Indeed for piped input the BGZF block file offsets weren't even calculated.
