### ISSUE TITLE
Add header to depth region

### ISSUE THREAD

**Issue by moonso** [lomereiter/sambamba#145]
Hello,

it would be nice with a header line in the output of ```sambamba depth region```.
My output no looks like:
```
1       69089   70007   1-69090-70007   0       +       CCDS30547.1     OR4F5   30      4.06972 0.326797        0       ADM1003A2
1       367657  368596  1-367658-368596 0       +       CCDS41220.1     OR4F29  0       0       0       0       ADM1003A2
1       621094  622033  1-621095-622033 0       -       CCDS41221.1     OR4F16  0       0       0       0       ADM1003A2
```

I am a bit confused about the 9:th column, what does '30' mean in this case?

**Comment by lomereiter** [comment]
That should be mean coverage.
Given that I myself had to pick into the source code to answer this, your suggestion is very reasonable :)

**Comment by moonso** [comment]
Ok, but then the mean coverage is calculated based on all reads, regardless of mapping quality etc?

**Comment by lomereiter** [comment]
All reads that overlap the region and pass the filter `-F` - in it you can set the desired threshold for mapping quality.

**Comment by moonso** [comment]
Thanks alot for the clarification!

**Comment by moonso** [comment]
Maybe we should close this when the header is in place...

**Comment by moonso** [comment]
Hi,

I am still a bit confused about that number, they are allways integers so it should not be mean coverge but maybe number of reads that cover the region and pass the filters in ```-F```?

**Comment by lomereiter** [comment]
Oops, indeed. Your guess is correct. The first number is read count, after that comes mean coverage.

**Comment by lomereiter** [comment]
I added the header, first three fields have fixed names, the rest of fields in the input BED file is named simply as `F<k>` because one can't guess what they contain; the column for coverage threshold `T` is named `percentage<T>`. Below is an example.
```
# chrom	chromStart	chromEnd	F3	F4	readCount	meanCoverage	percentage5	percentage20	sampleName
```
