### ISSUE TITLE
Quality treshold in sambamba depth

### ISSUE THREAD

**Issue by moonso** [lomereiter/sambamba#146]
I noticed that ```sambamba depth``` use only high quality reads when reporting coverage.
Is there anyway to see the default value of this parameter.  

When using ```--min-base-quality 0```  the same coverage is reported as I get without this flag, but with ```samtools tview``` I can see that there are multiple low quality reads that covers the positions of interest.

**Comment by lomereiter** [comment]
Hi, you should use `-F` flag instead. The default filter for reads is set to exclude those with zero mapping quality, duplicates, and reads that failed QC (these are the reasonable defaults I've seen in bedtools). 
Minimum base quality is zero by default and is applied on a per-base and not per-read basis. Sorry that documentation is unclear on this.

**Comment by moonso** [comment]
Thank you for the explanation, looking forward to see ```sambamba depth```in the documentation :)
