### ISSUE TITLE
Inconsistent results with sambamba depth

### ISSUE THREAD

**Issue by moonso** [lomereiter/sambamba#147]
Hi,

I found a strange problem.
When using ```sambamba depth region``` and a bed file with exons from ccds, ```sambamba``` gives different results depending on if we use the file with all exons or just one region.
If we look at one region only the file looks like
```
$ cat small_region.bed
10	46339772	46339841	10-46339773-46339841	0	-	CCDS7215.1	AGAP4
$ sambamba depth region -t 8 sample.bam -L small_region.bed
Processing reference #10 (10)
10	46339772	46339841	10-46339773-46339841	0	-	CCDS7215.1	AGAP4	2	0.768116	ADM1003A2
```

But when running sambamba on the whole bed file and we look at coverage for the same region:
```
$ sambamba depth region -t 8 sample.bam -L CCDS.current.bed -o sambamba_regions.csv
$ grep 46339772 sambamba_regions.csv
10	46339772	46339841	10-46339773-46339841	0	-	CCDS7215.1	AGAP4	569	40.0551	ADM1003A2
```
We see a completely different coverage result...
We inspected the bam file with ```samtools tview``` and it looks like the first result is correct, it is very low coverage.  
I understand that this might be hard to replicate without the original data but do you have any idea what might cause the problem?

Thanks

**Comment by lomereiter** [comment]
Thanks, it turned out that unsorted BED files weren't handled correctly.
