### ISSUE TITLE
Comparison of the result of marking duplicates between Sambamba and Picard

### ISSUE THREAD

**Issue by FrankFeng** [lomereiter/sambamba#148]
Hello, 

Sambamba is much faster than Picard when marking duplicates, which is excellent. However, I saw slight difference in the numbers of reads marked as duplicate between Sambamba and Picard, with using Sambamba's flagstat command. Do you have any ideas why there is such a difference? Thanks.

The flagstat with the BAM processed by Picard-1.134 shown below:

```
34021072 + 0 in total (QC-passed reads + QC-failed reads)
7442914 + 0 duplicates
33382234 + 0 mapped (98.12%:-nan%)
34021072 + 0 paired in sequencing
16961544 + 0 read1
17059528 + 0 read2
29996606 + 0 properly paired (88.17%:-nan%)
33045087 + 0 with itself and mate mapped
337147 + 0 singletons (0.99%:-nan%)
2084978 + 0 with mate mapped to a different chr
1426940 + 0 with mate mapped to a different chr (mapQ>=5)
```

The flagstat with the BAM processed by Sambamba v0.5.4 shown below:

```
34021072 + 0 in total (QC-passed reads + QC-failed reads)
7549201 + 0 duplicates
33382234 + 0 mapped (98.12%:-nan%)
34021072 + 0 paired in sequencing
16961544 + 0 read1
17059528 + 0 read2
29996606 + 0 properly paired (88.17%:-nan%)
33045087 + 0 with itself and mate mapped
337147 + 0 singletons (0.99%:-nan%)
2084978 + 0 with mate mapped to a different chr
1426940 + 0 with mate mapped to a different chr (mapQ>=5)
```

**Comment by FrankFeng** [comment]
The mapping was done with BWA-MEM, and as a results, there are 1420194  supplementary alignments in the BAM file marked as 0x800  -- Does it contribute to the difference of marking duplicates between Sambamba and Picard? Thanks.

**Comment by lomereiter** [comment]
Hi, your guess is correct, there was a bug with handling supplementary alignments. 
Please check if the [latest binary](https://dl.dropboxusercontent.com/u/7916095/sambamba_31_01_2015) fixes your problem.

**Comment by FrankFeng** [comment]
Hi @lomereiter , I tried the latest binary, and it gave me the same result as Picard-1.134. Thank you very much!
