### ISSUE TITLE
basequality filter for sambamba depth region/window?

### ISSUE THREAD

**Issue by melferink** [lomereiter/sambamba#154]
Hi Artem,

Is it possible to filter on basequality for sambamba depth region/window?
I see the option -p for depth base but not for region/window. 
Also, I can not find  basequality in the code for the filter (-F) option.

Did I miss it, or is it not possible (yet)?

Btw. the tool is working great! Keep up the good work!

Greetz,
Martin

**Comment by lomereiter** [comment]
Hi Martin,

I've added (minimum) base quality filtering for all modes.
It's currently not possible to filter out reads based on their base qualities, I'm not sure how useful that could be, but maybe I should add something like `avg_base_quality` / `min_base_quality`   / `median_base_quality` to the `--filter` option.

**Comment by melferink** [comment]
Thanks!

**Comment by melferink** [comment]
Hi Artem,

I did some small test, and I am afraid the -q option is not working properly (at least not the way I expected it to do ;) ).

It appears that the q filtering is fixed on base 2 only (irrespective of orientation of the read) and when this base does not meet the threshold, the entire reads (thus all bases) are removed from the analysis. 
Quality of other bases (besides base 2), does not influence the filtering/calculations even if they are below the threshold.

The way I see the filtering is that each base in a read thats lower than the quality is removed, the remaining bases should be used.
So a read with JJJJJJAJJJ  should be counted as 10 with no filterings, and as 9 with filtering -q 33.

Let me know if you need more input (or test files)!

Greetz

**Comment by lomereiter** [comment]
Oops, you are right. Thanks for the testing.

**Comment by lomereiter** [comment]
OK, I made the changes so that now bases are counted according to your suggestion. A read is counted only if it has at least one good quality base in the region. Indels are just ignored.
