### ISSUE TITLE
mpileup running error

### ISSUE THREAD

**Issue by jjjscuedu** [lomereiter/sambamba#155]
My command is like this:
sambamba_v0.5.6/./sambamba mpileup -t 25 -o sambamba.var.flt.vcf S246.merged.bam S247.bam S248.bam S249.bam S250.bam S251.bam S252.bam S253.bam S254.bam --samtools -u -t DP -f index/Ntab.fa --bcftools call -vm -O v

However, there is no content in final sambamba.var.flt.vcf file, and the log file also has some errors:

executing] /gpfs01/software/bio/bin/samtools mpileup /tmp/687434.tmpdir/sambamba-pid56822-iyrw/25 -l /tmp/687434.tmpdir/sambamba-pid56822-iyrw/25.bed -t DP -f /gpfs01/home/jingjing/project/tobacco/index/Ntab.fa | /gpfs01/software/bio/bcftools-1.2//bcftools call -v -m -O v| /gpfs01/software/bio/sambamba_v0.5.6/./sambamba strip_bcf_header --vcf| /gpfs01/softwa
re/bio/sambamba_v0.5.6/./sambamba lz4compress
[opened FIFO for writing] /tmp/687434.tmpdir/sambamba-pid56822-iyrw/25
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
Failed to open -: unknown file type
Failed to open -: unknown file type
Failed to open -: unknown file type

Can anyone give me some suggestions?

Jingjing

**Comment by lomereiter** [comment]
`bcftools call` expects a file in BCF/VCF format, so you should add `-u` to the list of `samtools` command-line parameters.

**Comment by lomereiter** [comment]
Ouch, I see that it's there. So it's parsing error on my side, reopening.

**Comment by jjjscuedu** [comment]
Thanks.

It is OK now.

It seems it should add -g or -v to set the output format of samtools.
