### ISSUE TITLE
SNP identification for multiple sample 

### ISSUE THREAD

**Issue by jjjscuedu** [lomereiter/sambamba#156]
sambamba_v0.5.6/./sambamba mpileup -t 25 -o sambamba.var.flt.vcf S246.merged.bam S247.bam S248.bam S249.bam S250.bam S251.bam S252.bam S253.bam S254.bam --samtools -ug -t DP -f index/Ntab.fa --bcftools call -vm -O v

I want to identify SNP for multiple samples. However, using above command, only genotype for one sample is output:
# CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  /tmp/687444.tmpdir/sambamba-pid52073-gkxq/1

Chr01   8501    .       TTTGTTGTTGTTGTTGTTGTTGTT        TTTGTTGTTGTTGTTGTTGTTGTTGTT     8.84303 .       INDEL;IDV=18;IMF=0.6;DP=29;VDB=0.000390739;SGB=-0.692562;MQSB=1;MQ0F=1;AC=2;AN=2;DP4=1,0,7,15;MQ=0      GT:PL:DP        1/1:35,56,0:23
Chr01   18477   .       G       A       21.7993 .       DP=4;VDB=0.06;SGB=-0.453602;MQSB=1;MQ0F=0.5;AC=2;AN=2;DP4=0,0,1,1;MQ=27 GT:PL:DP        1/1:49,6,0:2
Chr01   18490   .       A       G       52      .       DP=9;VDB=0.0117389;SGB=-0.556411;RPB=0;MQB=0.375;MQSB=1;BQB=0.5;MQ0F=0;ICB=1;HOB=0.5;AC=1;AN=2;DP4=1,1,4,0;MQ=38        GT:PL:DP        0/1:86,0,27:6
Chr01   18498   .       A       G       141     .       DP=12;VDB=1.93216e-05;SGB=-0.670168;RPB=1;MQB=1;MQSB=0.277778;BQB=1;MQ0F=0;AC=2;AN=2;DP4=0,1,9,1;MQ=43  GT:PL:DP        1/1:173,0,6:11
Chr01   18507   .       C       T       99      .       DP=18;VDB=1.74965e-05;SGB=-0.676189;RPB=0.310516;MQB=0.0388261;MQSB=0.216663;BQB=0.492881;MQ0F=0.111111;ICB=1;HOB=0.5;AC=1;AN=2;DP4=2,3,11,0;MQ=31      GT:PL:DP        0/1:134,0,22:16

Can anyone give me some suggestions?

**Comment by lomereiter** [comment]
Sambamba currently doesn't take filenames into account, and relies on read group information (which is often added by the aligner nowadays). I realize that's not always convenient, so I'll keep this issue open.

You can do something along these lines:
1. Extract SAM header from any of the files: `samtools view -H S247.bam > header.sam`
2. Open it in an editor and add one `RG` line per file (example: https://www.biostars.org/p/88323/)
3. Run `samtools merge -r -h header.sam - S2*.bam | sambamba mpileup /dev/stdin ...`

**Comment by inti** [comment]
Hello @jjjscuedu , have a look at https://github.com/ekg/bamaddrg for adding read-groups to multiple files and streaming the data into another tool.
