### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by gpcr** [lomereiter/sambamba#157]
Hi ,

Iam getting error while compiling sambamba on ubuntu 14.04

...
mkdir -p build/
rdmd --force --build-only -IBioD -g -L-Lhtslib -L-l:libhts.a -L-l:libphobos2.a -ofbuild/sambamba main.d
sambamba/utils/common/filtering.d(327): Error: no property 'representation' for type 'string'
cram/reader.d(107): Error: no property 'map' for type 'Zip!(CramSliceDecoder!(UndecodedSliceRange), Repeat!(CramReader), Repeat!(ubyte[] function(ulong)))'
cram/reference.d(91): Error: no property 'map' for type 'Zip!(CramSliceDecoder!(UndecodedSliceRange), Repeat!(PositionChecker), Repeat!(IBamSamReader), Repeat!(ubyte[] function(ulong)))'
/usr/include/dmd/phobos/std/numeric.d(1606): Deprecation: read-modify-write operations are not allowed for shared variables. Use core.atomic.atomicOp!"+="(s, e) instead.
/usr/include/dmd/phobos/std/numeric.d(1632): Deprecation: read-modify-write operations are not allowed for shared variables. Use core.atomic.atomicOp!"*="(e, f) instead.
sambamba/pileup.d(235): Error: module std.format import 'text' not found
sambamba/view.d(320): Error: no [] operator overload for type ReferenceSequence
sambamba/view.d(345): Error: template instance sambamba.view.sambambaMain!(CramReader).sambambaMain.processAlignments!(ReadCounter) error instantiating
sambamba/view.d(192):        instantiated from here: sambambaMain!(CramReader)
sambamba/view.d(320): Error: no [] operator overload for type ReferenceSequence
sambamba/view.d(352): Error: template instance sambamba.view.sambambaMain!(CramReader).sambambaMain.processAlignments!(BamSerializer) error instantiating
sambamba/view.d(192):        instantiated from here: sambambaMain!(CramReader)
sambamba/view.d(320): Error: no [] operator overload for type ReferenceSequence
sambamba/view.d(357): Error: template instance sambamba.view.sambambaMain!(CramReader).sambambaMain.processAlignments!(CramSerializer) error instantiating
sambamba/view.d(192):        instantiated from here: sambambaMain!(CramReader)
sambamba/view.d(320): Error: no [] operator overload for type ReferenceSequence
sambamba/view.d(364): Error: template instance sambamba.view.sambambaMain!(CramReader).sambambaMain.processAlignments!(SamSerializer) error instantiating
sambamba/view.d(192):        instantiated from here: sambambaMain!(CramReader)
sambamba/view.d(320): Error: no [] operator overload for type ReferenceSequence
sambamba/view.d(366): Error: template instance sambamba.view.sambambaMain!(CramReader).sambambaMain.processAlignments!(JsonSerializer) error instantiating
sambamba/view.d(192):        instantiated from here: sambambaMain!(CramReader)
sambamba/view.d(320): Error: no [] operator overload for type ReferenceSequence
sambamba/view.d(368): Error: template instance sambamba.view.sambambaMain!(CramReader).sambambaMain.processAlignments!(MsgpackSerializer) error instantiating
sambamba/view.d(192):        instantiated from here: sambambaMain!(CramReader)
make: *** [all] Error 1

**Comment by lomereiter** [comment]
Hi, please use LDC for compilation. DMD is not supported anymore.
