### ISSUE TITLE
Again, Inconsistent results with sambamba depth

### ISSUE THREAD

**Issue by refaelkohen** [lomereiter/sambamba#159]
Hello, 

I use with sambamba depth v0.5.7
There is problem with the results of sambamba depth:
When I use with part of bed file (of regions) I get different results from the case that I use with all bed file.

I upload the input and output files to our server (49G): 
You can downlaod the files with the command:
wget -r --no-parent http://incpm-2.weizmann.ac.il/bioinfo/sambamba/ 

I use with the commands:
For bed file with all regions:
sambamba depth region     -t 40    -L in_part.bed    ERR224450.1.bam > out_part &
For bed file with part of regions:
sambamba depth region     -t 40    -L in_all.bed       ERR224450.1.bam > out_all &

Thank you, 
Refael.

**Comment by lomereiter** [comment]
Thanks for providing me with the complete test case. Unfortunately, I haven't properly tested the fix to #147, it turned out to be incomplete.

(Also, could you please in the future reopen old issues instead of creating new ones?)

**Comment by refaelkohen** [comment]
This is work fine now.
Thank you on your very fast software and very fast response :)
Refael.
