### ISSUE TITLE
Complex and long filter expressions

### ISSUE THREAD

**Issue by carze** [lomereiter/sambamba#161]
Is it possible to read from a file a long or complex filter expression? 

I am currently trying to filter on a high number of read names and am running into too many arguments Unix errors.

**Comment by pjotrp** [comment]
Should be fairly easy to create that facility using Sambamba's source. If you want to try to add that feature yourself we can make suggestions. Can you post an example?

**Comment by carze** [comment]
I haven't worked with D before but I'd definitely be willing to take a shot at it when I get some free time.

I was hoping to leverage sambamba's fast BAM processing to filter on CIGAR string in a bit of a more complex manner. An example would be something like given a CIGAR string could we return all reads that have 60 or more alignment matches. I think you can currently do this by parsing the CIGAR string looking for something like this:

60M

but if your CIGAR string looks like this (where alignment matches are not contiguous):

40M2D30M

I did not come across a way to get this read returned with the given filtering support in place. If I am wrong here and this is already possible that would take care of my specific use case.

**Comment by lomereiter** [comment]
Pjotr and I decided that building a full-blown interpreter into sambamba doesn't make much sense, and I argue that long filtering expression almost necessarily would lead to unbearably long execution times. 

So the compromise is that we can save you some time by providing a minimally working code to get started. Please download LDC or DMD, pull [BioD](https://github.com/BioD/BioD) and fit [this script](https://gist.github.com/lomereiter/e4f4f2b0a6cf9cee4287) to your needs. Feel free to ask here for further help.
