### ISSUE TITLE
Can sambamba merge sam files? bgzf error

### ISSUE THREAD

**Issue by bcosc** [lomereiter/sambamba#162]
Hi I'm trying to merge 82 sam files like this:

sambamba_v0.5.4 merge -t 16 output.sam file1.sam file2.sam ... file 82.sam

and got the error:

sambamba-merge: Error reading BGZF block starting from offset 0: wrong BGZF magic

**Comment by lomereiter** [comment]
Hi, SAM files are not supported in `merge` currently.
