### ISSUE TITLE
Sort BAM with incorrect bin

### ISSUE THREAD

**Issue by tylo42** [lomereiter/sambamba#163]
I have a BAM where the bin was set incorrectly. When running `sambamba sort` the following error message is printed and sorting is aborted:

 > sambamba-sort: Bin in read with name 'XXX' is set incorrectly (5784 instead of expected 90)

This corresponds to https://github.com/biod/BioD/blob/master/bio/bam/bai/indexing.d#L251.

On the same BAM file (once sorted with samtools) an index can be built with `sambamba index` since `--check-bins` is off by default. Would it be possible to add an argument similar to `--check-bins` for `sambamba sort`?

For comparison, samtools sorts the same BAM file by leaving the bin incorrect.

**Comment by lomereiter** [comment]
The tools that write BAM now set the bin correctly prior to writing the records. The option like `--check-bins` doesn't make much sense when one can simply fix the records (`index` doesn't write BAM, so it can only check).

**Comment by tylo42** [comment]
Good point about fixing the records. I tested it out and it works beautifully. Thank you so much for your quick response and fix!
