### ISSUE TITLE
reheader?

### ISSUE THREAD

**Issue by travc** [lomereiter/sambamba#166]
Any plans to add a 'reheader' command.

If you don't think that sambamba would handle it better/faster than samtools, then fair enough, but you might want to mention that it in the docs.  Otherwise... Being able to change sample names (or other header info) faster using sambamba would be sweet.

**Comment by lomereiter** [comment]
The performance of 'reheader' for BAM files mainly depends on disk reading/writing speed, so indeed it can't be handled significantly faster than samtools.
I have no idea where to put it in the docs, though. If you do, please make a suggestion (or even a pull request).
