### ISSUE TITLE
sambama depth base in v0.5.8 doesn't work with a regions file

### ISSUE THREAD

**Issue by roryk** [lomereiter/sambamba#167]
v0.5.8:

```
./sambamba depth base -L small_MIG.bed align/NA12878-1/NA12878-1-sort.bam | head -3
Processing reference #1 (1)
REF	POS	COV	A	C	G	T	DEL	REFSKIP	SAMPLE
```

v0.5.6
```
sambamba depth base -L small_MIG.bed align/NA12878-1/NA12878-1-sort.bam | head -3
Processing reference #1 (1)
REF	POS	COV	A	C	G	T	DEL	REFSKIP	SAMPLE
1	69296	1	0	1	0	0	0	0	NA12878-1
1	69297	1	1	0	0	0	0	0	NA12878-1
```

**Comment by lomereiter** [comment]
Hi Rory,
Please check the base qualities in a BAM viewer. The bases used to be counted incorrectly, namely, all bases in a region would be counted for every read that has at least one good base in the region (see https://github.com/lomereiter/sambamba/commit/15f75bb37898689c21ccec0635acd6d3356ec4fd)

**Comment by roryk** [comment]
Hi Artem,

Hmm-- I don't think that is it, I get 0 counts even if I run a ton of regions. I dissected out one region that looks like it should be generating counts:

v0.5.8
```
sambamba depth base -L test.bed test.bam | wc -l
1
```

v0.5.6
```
sambamba depth base -L test.bed test.bam | wc -l
149
```

http://dl.dropbox.com/u/2822886/Screenshots/e6lk6pbwr4gy.png is a screenshot of the alignments in the region 1:979489-979637.

I put up the test files here:

https://dl.dropboxusercontent.com/u/2822886/sambamba-depth-test-files.tar

**Comment by lomereiter** [comment]
Ok, I'll look into this.

**Comment by roryk** [comment]
Thanks! You've been great about responding to issues, I really appreciate it.

**Comment by lomereiter** [comment]
This bug was introduced by my awful fix of another bug (https://github.com/lomereiter/sambamba/commit/6d1f5a340c06abc0929ddb781288a7c0dd03068f), BED parser should be completely rewritten once I find time for that.

**Comment by roryk** [comment]
haha-- I know that pain. Thanks for the quick fix Artem.
