### ISSUE TITLE
problem with --tmpdir= in sambamba sort

### ISSUE THREAD

**Issue by inti** [lomereiter/sambamba#170]
Hi,
When I added the option --tmpdir to sambamba sort it gave me issues. No error message but it just froze without using any CPUs. Removing the option and it works just fine. I am using version v0.5.8 
thanks in advance,

**Comment by lomereiter** [comment]
Hi,
I could reproduce the issue a few times last evening, but during later attempts it suddenly disappeared =\
If you can reproduce it, please tell whether the directory `sambamba-pidXYZW-????` is created in the provided tmpdir (where XYZW is PID you can look up in `ps a` output).
