### ISSUE TITLE
sambamba depth base -L bed problem

### ISSUE THREAD

**Issue by parlar** [lomereiter/sambamba#172]
I'm encountering some odd behavior running "sambamba depth base -L bed" - have tried both the 0.5.8 and 0.5.7 versions. Unfortunately, compiling from master fails on my centos 7.1 machine (using ldc2-0.14 and 0.16 beta2) so I have not been able to try it.

I'm getting data only for some of the chr:s represented in the bed (>= chr12) for 0.5.7, no data from 0.5.8. 

Using "depth region" seems ok though. 

Do you need more info?

cheers,

Pär

**Comment by lomereiter** [comment]
Hi Pär,
Please provide the bed file, the behavior in master should be the same as in 0.5.7.

**Comment by lomereiter** [comment]
I tested various releases on the BED file you've sent me over e-mail, and I confirm that versions 0.5.5 through 0.5.8 are buggy (thanks to adding support for unsorted BEDs without proper testing...), but as of latest commit the behavior is back to normal (that in 0.5.4).

**Comment by parlar** [comment]
Thanks, is it possible to put it into a new release? For some reason, compilation of sambamba failed when I tried.
