### ISSUE TITLE
mis-match rate decrease with downsampling

### ISSUE THREAD

**Issue by isthisthat** [lomereiter/sambamba#173]
Hi Artem,
Wanted to get your thoughts on this one. We've used `sambamba view -s` and `markdup` to progressively downsample a bam to different depths (to look at how metrics correlate with depth). Most of the trends make sense but we've noticed that mis-matches per (non-duplicate) read decreases with higher depth. It is a small decrease but consistent. We would expect it to be constant. Our hypothesis is that it has to do with the way duplicates are marked. If the read with fewest errors from a set of duplicates is selected as the one to be not flagged as duplicate, and if downsampling happens to throw that read away, then your "new" non-duplicate read would be one with more errors than before. I guess this depends on the aligner more than anything. Is there anything else that could cause this? Any comments?
Thanks for your continued support.
Stathis

**Comment by lomereiter** [comment]
Hi Stathis,

Thanks for this interesting observation. Your hypothesis totally makes sense, as the non-duplicate representative is selected on the basis of its average base quality. If you're interested, you can test it by replacing `best_k` selection [here](https://github.com/lomereiter/sambamba/blob/2ee35899b483ae8fdb8746273131808b50639fa1/sambamba/markdup.d#L813-L820) with setting `best_k` to `0` or a randomly chosen value (also [here](https://github.com/lomereiter/sambamba/blob/2ee35899b483ae8fdb8746273131808b50639fa1/sambamba/markdup.d#L879-L883) for single reads); not sure about the former, but the latter should lead to constant error rate vs depth.

**Comment by isthisthat** [comment]
That makes sense. Subtle but interesting observation. Thanks for the pointers to the code as well.
