### ISSUE TITLE
zero cov output problem

### ISSUE THREAD

**Issue by parlar** [lomereiter/sambamba#175]
Hi again,

sambamba_v0.5.9 depth base -L bed -z (or --report-zero-coverage) bam 
does not seem to output zero-coverage bases?

cheers

Pär

**Comment by parlar** [comment]
Sorry for bumping this issue. I guess that you have your hands full - as everyone. I'm just wondering if you were planning to look at this or if if you feel that it has a lower priority. Then I'll invest the time to make a work-around.

**Comment by lomereiter** [comment]
Hi Pär, your guess is correct, but I look forward to making `depth` tool production-ready. A test case from your side would be very helpful.

**Comment by parlar** [comment]
Sure! Just let me know. A bam file, targets.bed, and a reference depth call output using bedtools and the same input - would that be ok?

**Comment by lomereiter** [comment]
Yes, that would be perfect.

**Comment by parlar** [comment]
I'll make it available then and send you a link.

**Comment by lomereiter** [comment]
closing as duplicate of #225
