### ISSUE TITLE
index issue with sorted bam

### ISSUE THREAD

**Issue by OAbio** [lomereiter/sambamba#179]
I am trying to index a sorted file, but getting an error "sambamba-index: BAM file is not coordinate-sorted: read 'somethingA' must be before read 'somethingB (at virtual offset 457209108/15483)". When I pull out these two reads, they seem to be duplicates with identical coordinates. Interestingly, samtools index has no issue with the same file. Any thought appreciated, thanks

OA

**Comment by lomereiter** [comment]
Hi, thanks for the report. I have no idea what may cause this, could you please upload the file to somewhere?

**Comment by OAbio** [comment]
this is a test file that I have been playing with for QC, unfortunately, I cannot send this one out. I will try to reproduce the issue with public data. I will let you know when I have something.

**Comment by lomereiter** [comment]
Hi, I was just hitting a similar thing while working on another bug, and the reason there was seemingly the buggy garbage collector (which I try to avoid anyway). So I'd like to ask you for more details:
1) Is the error reproducible on this particular file any time you run index?
2) If yes, is it always the same record or a different one each time?

**Comment by OAbio** [comment]
Sorry for the late delay. I isolated the issue to a sorting error indeed at the contig level. Issue has been resolved for me so far. Thank you for the support.
