### ISSUE TITLE
core dump in 0.5.5 and 0.5.8

### ISSUE THREAD

**Issue by lonestar21** [lomereiter/sambamba#181]
Hi.
When I try and merge some bisulfite novoalign bams I get a core dump.   I've tried this on Centos5 and Centos 6 with the 2 versions above and I consistently get this error soon after the run begins.

# xhost11 /projects/rcorbettprj2/novoAlignBioQC/A27712 $ 
/gsc/software/linux-x86_64/sambamba-0.5.5/sambamba_v0.5.5 merge -p A27712.bam ./*sorted.bam; 
Segmentation fault

any ideas?

**Comment by lonestar21** [comment]
Hmmm. I was able to run some other samples successfully.  There is quite likely a problem with one of the bams I am trying to merge.

**Comment by lomereiter** [comment]
Does any of your files contain long reads (~10K bases)? They weren't handled properly until recently (#182).

**Comment by lonestar21** [comment]
Hi Artem,
Nope, just 125bp illumina reads.  I suspect one of the bams were truncated (we've had some network errors lately).   I'll try re-running the alignment and see if that fixes things.  It might take a few days (novoalign after all).

**Comment by lonestar21** [comment]
Hi Artem,
As expected, having re-run the alignments allows me to successfully to merge/dupmark the bams. There must have been something wrong with my original bams.
