### ISSUE TITLE
Problems with merging pacbio bam files

### ISSUE THREAD

**Issue by nspies** [lomereiter/sambamba#182]
I get this error:

```
sambamba-merge: BAM file is not coordinate-sorted: read 'm[??7?m??`??' must be before read 'm150209_042724_42177R_c100779832550000001823165208251590_s1_p0/101549/11999_40392' (at virtual offset 879295/0)
```

When I try to run this command:

```
sambamba merge test.bam BWA-MEM_Chr21_HG003_merged_11_12.sort.bam BWA-MEM_Chr22_HG003_merged_11_12.sort.bam
```

(Files from here: ftp://ftp-trace.ncbi.nih.gov//giab/ftp/data/AshkenazimTrio/HG004_NA24143_mother/PacBio_MtSinai_NIST/CSHL_bwamem_bam_GRCh37)

I'm not sure if there are problems with the read lengths from pacbio bams, but samtools merge works fine. ```sambamba view``` on the file merged from samtools works great.

**Comment by lomereiter** [comment]
Thanks for reporting, that's indeed a serious bug. Somehow I totally forgot about existence of large reads when I was adding on-the-fly indexing feature — should work now.
