### ISSUE TITLE
Abount markdup's input and output

### ISSUE THREAD

**Issue by chulghim** [lomereiter/sambamba#183]
1) input bam must be sorted by coordinate ?
Can i use  bwa mem's result directly as input of sambamba markdup?

2) Is ouput bam sorted automatically by coordinate?   or i must sort after markdup ?

**Comment by lomereiter** [comment]
1) Yes, it should be sorted. No, you can't use bwa input directly, I know that samblaster was created exactly for this use case.
2) The output remains in the same order, so no need to sort.
