### ISSUE TITLE
skip regions in depth region cmd

### ISSUE THREAD

**Issue by lpantano** [lomereiter/sambamba#184]
Hi,

thanks for this tool, is awesome!

I am using this in bcbio-nextgen framework to make coverage reports. I noticed that some regions are not in the output using this command:

`sambamba  depth region  -F
 "not unmapped" -t 1 -C 200 -T 1 -T 5 -T 10 -T 20 -T 40 -T 50 -T 60 -T 70 -T 80 -T 100 -L region.bed  file.bam`

Is that expected? if yes, is there any way to keep all regions?

thanks a lot!

**Comment by lpantano** [comment]
another idea is that maybe regions with > max_coverage are skipped?

**Comment by lpantano** [comment]
I see that maybe is that here:

https://github.com/lomereiter/sambamba/blob/master/sambamba/depth.d#L606

any chance that it could return the region with the max_cov value? maybe another option for that?

I like the idea to stop counting if you have more than 200 reads, but it would be good to have the region in the output with this limit.

**Comment by lomereiter** [comment]
Hi,

Sorry for too terse documentation. The way to keep all regions would be to skip `-C` option, as you deduced from the code.

Are you bumping into any sort of speed issues due to high coverage? It seems from your command line that  providing support for `-T A,B,C,D,...` is of higher priority ;-)

**Comment by lpantano** [comment]
hi, 
thanks  a lot for the reply!

I will test without the -C, but is becoming slow, but need to really see the exact time to decide if it would affect or not. Will keep you post this week, and close if there is no real problem in speed!

thanks!
