### ISSUE TITLE
Filter support for chimeric alignments

### ISSUE THREAD

**Issue by isthisthat** [lomereiter/sambamba#185]
Currently it's not straightforward to filter for chimeric alignments in a bam (mate mapped to a different chromosome). It would be very helpful to enable that term in sambamba filtering. It is already reported in `flagstat` so it would relatively easy to port? :) Thank you very much for your continued support.

**Comment by lomereiter** [comment]
I'd say it was trivial to port, just want to highlight the tiny difference compared to `flagstat` in that the new flag allows for secondary and supplementary alignments (those can be filtered out by appending `and not (secondary_alignment or supplementary)`).

**Comment by pjotrp** [comment]
@isthisthat do you mind signing up the mailing list so we can discuss the future of sambamba?

**Comment by isthisthat** [comment]
@pjotrp where do I sign up?

**Comment by pjotrp** [comment]
https://groups.google.com/forum/#!forum/sambamba-discussion
