### ISSUE TITLE
Handling of empty BED columns

### ISSUE THREAD

**Issue by robinandeer** [lomereiter/sambamba#187]
I have a BED file with an empty column (6th).

When I run Sambamba depth it only fills in "F3, F4, F5" etc. for the non-empty columns in the header of the output file. However the empty column is still preserved in the output so there's a mismatch between what the header refers to and the columns in the file.

**Comment by lomereiter** [comment]
Hi Robin,
I'm not very familiar with BED format peculiarities. Are they nowadays assumed to be strictly tab-delimited? (bedtools seems to require that) Currently the number of fields is counted by splitting first line on whitespace, that obviously leads to an issue with empty columns.

**Comment by robinandeer** [comment]
Interesting @lomereiter 

This is the [reference](https://genome.ucsc.edu/FAQ/FAQformat.html#format1) I've been using in the past and it doesn't say anything about tabs/spaces.

Perhaps it's fair to believe that columns must have some value and can't be left blank. Like the case with the "score" column where you put 0 unless you actually use it for a specific reason.

**Comment by pjotrp** [comment]
Inactive
