### ISSUE TITLE
Sambamba issues on Pacbio data

### ISSUE THREAD

**Issue by inumanag** [lomereiter/sambamba#190]
Hello!

Sambamba complains that the following PacBio sample is not sorted (and crashes with exit code 256):
http://bergmanlab.ls.manchester.ac.uk/data/tracks/dm3/dm3PacBio.bam

Execution of the following command:

	sambamba_v0.5.8 view -S -f bam -t 4 dm3PacBio.bam.sam -o dm3PacBio.sambamba.bam

produces:

	sambamba-view: BAM file is not coordinate-sorted: read 'β
	�u����X��4^og<k/��X��O- ��Y��o5�=w�"ϝO	... (more garbage)                       
	 must be before read 'm131127_112027_42175_c100604762550000001823112706171403_s1_p0/115130/0_31201' (at virtual offset 17404758/0)`

File seems to be sorted, and samtools has no problems parsing the file.

Best regards,
Ibrahim

**Comment by lomereiter** [comment]
Hi Ibrahim,
This bug is most likely already fixed in the master branch (see https://github.com/lomereiter/sambamba/issues/182), I've just realized it's not included in the latest release, which I promise to make within the next few days.
