### ISSUE TITLE
Run depth tool without any filter

### ISSUE THREAD

**Issue by mbootwalla** [lomereiter/sambamba#191]
Hi,

In the depth tool documentation it says that the tool runs with a default filter of 'mapping_quality > 0 and not duplicate and not failed_quality_control'. How do I run the depth tool with no filter at all? I want to get the per base depth using all of the reads without any filtering. I have noticed that for certain regions the per base depth is not reported even when using the -z option due to which the output from sambamba depth and samtools depth differs. I want to use sambamba depth tool for coverage analysis since it is a lot faster than samtools depth. Would appreciate any insights.

Thanks,

Moiz

**Comment by lomereiter** [comment]
Hi,
Empty filter specified through `-F` indeed didn't work, it's fixed now.
