### ISSUE TITLE
How to provide ldc2 libs on compile time?

### ISSUE THREAD

**Issue by biocyberman** [lomereiter/sambamba#192]
Guess this is an easy and quick thing to fix. I had to edit line 4 in Makefile it like so:
STATIC_LIB_PATH=-Lhtslib -Llz4/lib -L/path/to/ldc2/lib

Without the last `-L` parameter sambamba failed to compile because /usr/bin/ld says: 
```
/usr/bin/ld: cannot find libphobos2-ldc.a
/usr/bin/ld: cannot find libdruntime-ldc.a
```
What is the normal way to get those libs recognized automatically?

**Comment by pjotrp** [comment]
You need to give the full path for static libraries. We are working on shared library support which will make this problem go away. This work is being done in
https://github.com/genenetwork/guix-bioinformatics/blob/master/gn/packages/bioinformatics.scm

**Comment by biocyberman** [comment]
:+1: @pjotrp Nice work with sambamba. I throught the static libraries were chosen for some good reasons. One of them I can think of is the assurance of portability, and compatibility. AFAIK, this is how comercial software is doing. Thefore, another aproach to solve this is to distribute the LDC libraries together with sambamba, just like you did with `htslib` and `lz4`

**Comment by lomereiter** [comment]
@biocyberman there are good reasons, exactly which you mention. As far as I know some users run the tool on CentOS 5/6 without admin rights, and it's easier to just build a statically linked binary than to package everything properly (for a multitude of distros).
Regarding your question, you can also use `LIBRARY_PATH` environment variable which is picked up by GCC during linking.

**Comment by pjotrp** [comment]
@lomereiter That is only part of the story. Imagine all software compiled into a static ball. Systems would become quite unworkable.

Distributing binaries with static libraries included is a short-term fix and may work OK for non-root deployment. But when it comes to downloading binaries from different sources, I think this is a really *bad* idea: binaries can not be trusted unless they are tested, signed and from a trusted source. Even if I were to trust you I would hesitate to just install a binary (that might have been tampered with) on a hospital cluster containing human data - and this is exactly what is happening today and what downloads encourage. 

It is a fact that binary downloads are evil when it comes to transparency - even if they are considered common and convenient. We should at least offer alternatives. That is one reason why I am working on GNU Guix and adding a sambamba package. GNU Guix allows true FOSS only and it allows for deployment of shared libraries in a reproducible and trusted way. To me it is the preferred solution for sensitive data environments. The alternative is to get a signed binary from a trusted party - and that is not like we are doing it today.

**Comment by lomereiter** [comment]
@pjotrp: I certainly agree that binary downloads are evil from security point of view. Static linking is still fine with me, though, at least in the case where a binary is used to process datasets 1000x its size.

The alternative I offer is building from source, which is okayish but not exactly convenient, so very few seem to use it, preferring to save time and grab the binary.

Another recent alternative is [bioconda](https://bioconda.github.io/), which 
* already has `sambamba` package, but it currently just grabs the binaries, that could be improved;
* relies on Conda, which is much more popular than Guix and has a strong scientific community;
* has support for signing packages (which might be a bit flawed at the moment, but that again can be improved)
* doesn't have all the other shiny features but at least allows to install non-statically-linked stuff and get the job done, which is the most important for a researcher.

**Comment by pjotrp** [comment]
I am aware of bioconda, and I think it is useful. I may write a conda importer for guix, but that is a different discussion.
