### ISSUE TITLE
Sambamba mpileup isn't generating pileup results for multiple bams

### ISSUE THREAD

**Issue by pwaltman** [lomereiter/sambamba#196]
Maybe I'm misunderstanding what sambamba mpileup is doing, but even though I'm passing multiple bams (14; one per sample), the output states that it is processing 14 samples from 1 input file (example output below).

the command that I'm using to call sambamba mpileup is:

> sambamba mpileup \
>     -L handmade_gencode_v19_nochr.bed \
>     -t 32 \
>     -o variant_pileup \
>     $(ls bams/*.bam) \
>     --samtools "-f Homo_sapiens_assembly19.fasta"

and when I look at the partial output file (variant_pileup), it looks like I'm only getting info for one sample, e.g.:

> 1       11548   A       1       ^".     E
> 1       11549   A       1       .       B
> 1       11550   A       1       .       B
> 1       11551   T       1       .       A

However, when I run samtools mpileup by hand, it appears that I'm getting results for multiple samples, e.g.:

> 1       11548   A       0       \*       \*       0       \*       \*       0       \*       \*       1       ^".     E       0       \*       \*       0       \*       \*       0       \*       \*       0
>        \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       *
> 1       11549   A       0       \*       \*       0       \*       \*       0       \*       \*       1       .       B       0       \*       \*       0       \*       \*       0       \*       \*       0
>        \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       *
> 1       11550   A       0       \*       \*       0       \*       \*       0       \*       \*       1       .       B       0       \*       \*       0       \*       \*       0       \*       \*       0
>        \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       *
> 1       11551   T       0       \*       \*       0       \*       \*       0       \*       \*       1       .       A       0       \*       \*       0       \*       \*       0       \*       \*       0
>        \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       \*       0       \*       *

I'll admit that I'm a little new to SNV calling, so am I missing something? As I stated above, according to the output that I'm getting while sambamba mpileup is running, it is processing data for 14 samples in 1 input file, e.g. here is a snippet of the output from sambamba while executing:

> ...
> [executing] samtools mpileup /tmp/sambamba-fork-ypoNwa/14936 -l /tmp/sambamba-fork-ypoNwa/14936.bed -f  Homo_sapiens_assembly19.fasta| sambamba strip_bcf_header --vcf| sambamba lz4compress
> [mpileup] 14 samples in 1 input files
> <mpileup> Set max per-file depth to 571
> [ready] /tmp/sambamba-fork-ypoNwa/14935
> [ready] /tmp/sambamba-fork-ypoNwa/14936
> ...

**Comment by lomereiter** [comment]
[This thread on biostars](https://www.biostars.org/p/88323/) indicates that in `samtools mpileup` only BCF output groups samples according to RG tags, text output considers only filenames.

I filed a bug in `samtools`: https://github.com/samtools/samtools/issues/546
I suspect it can be solved fairly easily by calling `group_smpl` (same as [here](https://github.com/samtools/samtools/blob/3d792baf65fe61979525bc21d3dee46b6584814e/bam_plcmd.c#L563)) and appending `gplp.` before every `n`, `n_plp`, and `plp` in this branch of code: https://github.com/samtools/samtools/blob/3d792baf65fe61979525bc21d3dee46b6584814e/bam_plcmd.c#L586-L646)

**Comment by pwaltman** [comment]
OK, so it's an issue with samtools, rather than sambamba. Hopefully, they will resolve it quickly
