### ISSUE TITLE
Sambamba mpileup isn't limiting analysis to regions that are passed to it with the -L option

### ISSUE THREAD

**Issue by pwaltman** [lomereiter/sambamba#197]
In addition to the issue #I posted yesterday (about sambamba/samtools not generating results for multiple users when multiple bams are passed to it), it also appears that sambamba mpileup is limiting it's analysis to the regions that are specified to those that a user specifies when they pass a bed file with the "-L" parameter.

Same as the issue I posted about yesterday, the command that I'm using to call sambamba mpileup is:

> sambamba mpileup \
>     -L handmade_gencode_v19_nochr.bed \
>     -t 32 \
>     -o variant_pileup \
>     $(ls bams/*.bam) \
>     --samtools "-f Homo_sapiens_assembly19.fasta"

when I look at the partial output file (variant_pileup), it looks like I'm only getting info for one sample, e.g.:

> 1 11548 A 1 ^". E
> 1 11549 A 1 . B
> 1 11550 A 1 . B
> 1 11551 T 1 . A

However, the first set of regions in the bed file that I'm passing with the -L option is:

> 1       69090   70008   ENST00000335137.3_OR4F5 0       +
> 1       137620  139379  ENST00000423372.3_AL627309.1    0       -
> 1       134900  135802  ENST00000423372.3_AL627309.1    0       -
> 1       367639  368634  ENST00000426406.1_OR4F29        0       +
> 1       621058  622053  ENST00000332831.2_OR4F16        0       -

So, I don't really understand why I'm getting results in the region chr1:11548-11551.

Should I be passing a regions file (i.e. 1:69090-70008) instead of a bam? If so, then the sambamba command line documentation should probably be clarified, as it currently states:

> $ sambamba mpileup
> usage: sambamba-pileup [options] input.bam [input2.bam [...]]
>                        [--samtools <samtools mpileup args>]
>                        [--bcftools <bcftools call args>]
> ...
> Sambamba options:
> *_>          -L, --regions=FILENAME
>                     provide BED file with regions
>                     (no need to duplicate it in samtools args);
>                     all input files must be indexed
> *_>    ...

**Comment by lomereiter** [comment]
Hi, which versions of `sambamba` and `samtools` are you using? I've just tried to reproduce the issue on a couple of random BAM files, but couldn't: for me output starts from '1 69091 ...' as it should.

**Comment by sambrightman** [comment]
Possibly related to https://github.com/samtools/samtools/issues/79 and https://github.com/samtools/samtools/issues/282?

**Comment by pjotrp** [comment]
Reopen if it is still an issue
