### ISSUE TITLE
Segmentation fault (core dumped) when sorting

### ISSUE THREAD

**Issue by 6C3C41** [lomereiter/sambamba#199]
Hello,

## Error

Segmentation fault (core dumped) when sorting (at end of merge step)

`sambamba sort -n test1.bam`

## Attempts to fix

* Works on my OSX
* Multiple validated input .bam files all fail (and all work with samtools)
* Present on v0.5.9, v0.6.0 binaries
* Present when I compiled latest with LLVM D compiler (0.14.0 and 0.17.1)
* Not a ulimit issue

## System info

* AWS EC2
* Ubuntu 15.10, 4.2.0-34-generic
* gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)
* ldc2 as above, no compilation issues

## Additional information

* view works
* index does not work

Thank you in advance for considering my issue! I can provide a test file privately.

Andrew

**Comment by lomereiter** [comment]
Hi,

AWS instead of a custom setup should make debugging easier. Could you please export the image to .vmdk and share it through ftp/dropbox/gdrive/...? ([docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ExportingEC2Instances.html))

**Comment by 6C3C41** [comment]
## gdb

> Program received signal SIGUSR1, User defined signal 1.
> [Switching to Thread 0x7f9fb74bd700 (LWP 130518)]
> __lll_lock_wait ()
>    at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
> 135     ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.

**Comment by 6C3C41** [comment]
Hi,

Yes I will do this today. I provided output from gdb above in the mean time.

Andrew

**Comment by 6C3C41** [comment]
Hi,

Looks like I am unable to export my virtual machine due to some export limitations of AWS. I am attempting a workaround which likely won't won't. Is there another way to proceed?

**Comment by lomereiter** [comment]
Ok, can you then just make an AMI and share it?
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html
(my AWS account: 155656874964)

**Comment by 6C3C41** [comment]
I shared it.

**Comment by lomereiter** [comment]
Thanks, I can see it, will try to debug.

**Comment by lomereiter** [comment]
Sorry, but from my side the provided AMI seems to be horribly broken. I launched three different instances, and on all of them I couldn't even run `git clone` which died every time with a weird error `fatal: fetch-pack: unable to fork off sideband demultiplexer`.

I also checked that the binary release runs fine on `ami-26d5af4c` currently listed among https://docs.docker.com/machine/drivers/aws/#default-amis (also uses Ubuntu 15.10 with slightly older 4.2.0-18 kernel).

**Comment by 6C3C41** [comment]
Thanks for the effort. Sorry about the AMI issues, I have not run into them. I'm not sure how to proceed. Feel free to close the issue. Do you have any recommendations, for instance dependencies I could attempt re-installing, short of booting a new AMI?

**Comment by lomereiter** [comment]
I can only recommend making a new AMI, unfortunately. Prefer stable versions (e.g. Ubuntu 14.04), because people are running into all sorts of crazy bugs on 15.10 + EC2 ([1](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457), [2](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1534345), [3](https://bugs.launchpad.net/ubuntu-on-ec2/+bug/1514234)), and automate provisioning as much as possible (Dockerfile/Ansible/Chef/Puppet - whatever feels fancier).
