### ISSUE TITLE
Sambamba sort in pipe didn't return "correct" exit status

### ISSUE THREAD

**Issue by vladimirkovacevic** [lomereiter/sambamba#201]
I am running sambamba in the pipe with bwa mem and samblaster:
`/opt/bwa-0.7.13/bwa mem -M -R '@RG ID:1' -t 30 reference.fa 001.fastq.gz 002.fastq.gz | */opt/samblaster/samblaster -r -i /dev/stdin -o /dev/stdout *| /opt/sambamba_v0.6.0 view -t 8 -f bam -l 0 -S /dev/stdin | /opt/sambamba_v0.6.0 sort -t 8 -m 10GiB --tmpdir ./ -o out.bam -l 5 /dev/stdin`

The input I am providing is not supported by samblaster (too many sequences) so it throws exit(1) and pass no data on its stdout (to sambamba). In this scenario sambamba sort exits with code 0 (success) and creates even the output .bam file which is corrupted (contains 1.5MB, while input fastq files are ~50GB). 
How can I obtain an information about the wrong execution and corrupted data?

Thanks in advance!

**Comment by lomereiter** [comment]
Hi, if I understand correctly, BWA is to blame, according to Greg's explanation (https://github.com/GregoryFaust/samblaster/issues/19) so I'm closing this issue.
