### ISSUE TITLE
sambamba hang on ppc64le

### ISSUE THREAD

**Issue by sanketshah11** [lomereiter/sambamba#205]
We compiled sambamba v0.5.9, llvm-3.5.0 and ldc on Power PC  system running Red Hat 7.2.

It compiles, works, but hangs when running the view command.

Here is the Pstack:

Thread 2 (Thread 0x3fffb0bde240 (LWP 194527)):
#0  0x00003fffb0ffdd50 in pthread_cond_wait@@GLIBC_2.17 () from /lib64/power8/libpthread.so.0
#1  0x0000000010208538 in core.sync.condition.Condition.wait() ()
#2  0x00000000101c5fb4 in std.parallelism.TaskPool.pop() ()
#3  0x00000000101c5cf8 in std.parallelism.TaskPool.executeWorkLoop() ()
#4  0x00000000101c5b2c in std.parallelism.TaskPool.startWorkLoop() ()
#5  0x0000000010202fac in thread_entryPoint ()
#6  0x00003fffb0ff8728 in start_thread () from /lib64/power8/libpthread.so.0
#7  0x00003fffb0df7ae0 in clone () from /lib64/power8/libc.so.6
Thread 1 (Thread 0x3fffb10d4b10 (LWP 194526)):
#0  0x00003fffb0ff9b54 in pthread_join () from /lib64/power8/libpthread.so.0
#1  0x0000000010204550 in thread_joinAll ()
#2  0x00000000102232bc in rt_term ()
#3  0x00000000102235f4 in _d_run_main ()
#4  0x0000000010010ddc in main ()

**Comment by sanketshah11** [comment]
[test.zip](https://github.com/lomereiter/sambamba/files/224843/test.zip)

**Comment by sanketshah11** [comment]
Attached the small BAM file we used to test, it works fine on Intel x86, but hangs on IBM

**Comment by lomereiter** [comment]
Sorry to say it, but I'm not going to fix it. At the very beginning I cared about big-endian architectures, but eventually stopped, especially after OS X transitioned to x86_64. I need very convincing reasons to spend my time on supporting rare platforms instead of working on improvements for hundreds of people using x86, and the problem is only magnified by similar attitude on the side of compiler developers.

**Comment by sanketshah11** [comment]
Hi,

I understand your concerns, but this PPC platform is little-endian (ppc64le) .
It will be very helpful if you could look at it. I can provide as much help, details you need.

**Comment by lomereiter** [comment]
Ok, that makes life a bit easier.
Please start with running test suite of LDC as it's done here: https://github.com/ldc-developers/ldc/blob/release-0.17.1/circle.yml#L23-L40
If some of tests fail, submit that to their issue tracker. There seems to be some support added recently (https://github.com/ldc-developers/ldc/commit/c1c7846e749d363a8cc41b8b58cfd75f0e545d33), so you should you their master branch.
