### ISSUE TITLE
PG Header

### ISSUE THREAD

**Issue by ACEnglish** [lomereiter/sambamba#206]
Hello,

Is it possible to have mergedups populate the PG tag of the header?

Thanks

**Comment by plijnzaad** [comment]
Related to this, I read [here](https://lomereiter.wordpress.com/2012/07/03/gsoc-weekly-report-7/) that 

> the user can add/remove reference sequence, read group, or program information (corresponding to @SQ, @RG and @PG lines in a header).

Was this indeed implemented? This would be so useful to have! E.g. it would make things much more tractable if sambamba view could be told to append something like
`@PG    ID:sambamba     CL:sambamba view -h RPB3-a.bam --filter 'first_of_pair and template_length >= 70 and template_length <= 126'` to the `@PG`-lines in the header!

I could not find any documentation on this, so if it is not implemented, I would like to request this as a feature
