### ISSUE TITLE
Issue with sambamba installation with ldc

### ISSUE THREAD

**Issue by vd4mmind** [lomereiter/sambamba#209]
I installed the LDC as in the page [sambamba](https://github.com/lomereiter/sambamba)

Below is my bashrc profile for the paths
```
echo $PATH
/home/vdas/tools/ldc2-0.17.1-linux-x86_64/bin
echo $LD_LIBRARY_PATH
/home/vdas/tools/ldc2-0.17.1-linux-x86_64/lib:
```

Then I did the following in /home/vdas/tools directory

```
git clone --recursive https://github.com/lomereiter/sambamba.git
    cd sambamba
    make sambamba-ldmd2-64
```
Installation was in progress but I got the following error which means that there is an error in the make.

```
ldmd2 @sambamba-ldmd-release.rsp
/home/vdas/tools/ldc2-0.17.1-linux-x86_64/bin/../import/std/numeric.d(1616): Deprecation: read-modify-write operations are not allowed for shared variables. Use core.atomic.atomicOp!"+="(s, e) instead.
/home/vdas/tools/ldc2-0.17.1-linux-x86_64/bin/../import/std/numeric.d(1642): Deprecation: read-modify-write operations are not allowed for shared variables. Use core.atomic.atomicOp!"*="(e, f) instead.
gcc -Wl,--gc-sections -o build/sambamba build/sambamba.o -Lhtslib -Llz4/lib -Wl,-Bstatic -lhts -llz4 -Wl,-Bdynamic -l:libphobos2-ldc.a -l:libdruntime-ldc.a  -lrt -lpthread -lm
/usr/bin/ld: cannot find libphobos2-ldc.a
/usr/bin/ld: cannot find libdruntime-ldc.a
collect2: error: ld returned 1 exit status
make: *** [sambamba-ldmd2-64] Error 1
```
How do I get rid of this error to properly install the sambamba and then put the path in my bashrc so that I can run it for my automatic workflows. Thanks

**Comment by lomereiter** [comment]
Hi, use `LIBRARY_PATH` instead of `LD_LIBRARY_PATH`, it should work.

**Comment by vd4mmind** [comment]
But my `LIBRARY_PATH` is empty, I always put all the libs in the `LD_LIBRARY_PATH` , still is it recommended?

**Comment by lomereiter** [comment]
These environmental variables serve different purposes, the former is for compiler to find libs, the latter is for resolving dynamic library symbols at runtime.

**Comment by vd4mmind** [comment]
Ah ok thanks, I was not aware of that. so I did that and I get 2 warnings

```
test/sam.c: In function 'faidx1':
test/sam.c:169:5: warning: 'faidx_fetch_nseq' is deprecated (declared at ./htslib/faidx.h:94): Please use faidx_nseq instead [-Wdeprecated-declarations]
```

```
mkdir -p build/
ldmd2 @sambamba-ldmd-release.rsp
/home/vdas/tools/ldc2-0.17.1-linux-x86_64/bin/../import/std/numeric.d(1616): Deprecation: read-modify-write operations are not allowed for shared variables. Use core.atomic.atomicOp!"+="(s, e) instead.
/home/vdas/tools/ldc2-0.17.1-linux-x86_64/bin/../import/std/numeric.d(1642): Deprecation: read-modify-write operations are not allowed for shared variables. Use core.atomic.atomicOp!"*="(e, f) instead.
gcc -Wl,--gc-sections -o build/sambamba build/sambamba.o -Lhtslib -Llz4/lib -Wl,-Bstatic -lhts -llz4 -Wl,-Bdynamic -l:libphobos2-ldc.a -l:libdruntime-ldc.a  -lrt -lpthread -lm
```

So now I see a build directory with its contents
```
drwxr-xr-x 2 vdas DPT        2 Apr 27 12:16 build
-rw-r--r-- 1 vdas DPT 22626304 Apr 27 12:17 sambamba.o
-rwxr-xr-x 1 vdas DPT  6992093 Apr 27 12:17 sambamba
vdas@modhep-n1:~/tools/sambamba/build$
```
So the tool is properly installed and if I put it in the path it should work of my bashrc ? but how do I check the proper installation is made or not?

If I do` sambamba view ` it says command not found. I trying to run this command from inside the build folder. I have not yet put it in the `PATH` of the environment variables thought. So does it work?

**Comment by lomereiter** [comment]
Yes, you should add the build directory to the `PATH`:
```bash
export PATH=~/tools/sambamba/build:$PATH
```

**Comment by vd4mmind** [comment]
Yes done , I did and it is working, I just had to export the PATH and now it shows well. Thanks a ton. Please close the issue.
