### ISSUE TITLE
sambamba markdup generates index file older than bam file.

### ISSUE THREAD

**Issue by yoonkihoon** [lomereiter/sambamba#211]
There is some timing issue in sambamba markdup by using multiple threads. This is what I am guessing based on the complaints from GATK RealignTargetCreator.
I think this is tied to this issue (https://github.com/lomereiter/sambamba/issues/178). A thread generating index file is terminated before the threads writing a new bam file. This doesn't happens every single time, but it happens randomly.

**Comment by biorelated** [comment]
I have experienced a similar issue. I re-run the indexing and and markdup and noticed it generated a bam file with  a later time stamp. It had left me confused and I have not experienced it since then. Now that you mention it here as well i could recall. It would be worth investigating.

**Comment by lomereiter** [comment]
Well, all file handling happens in the main thread, so I don't see these two issues as linked.
Do region queries operate properly with the generated index? Does `samtools idxstats` give reasonable values? (reindex with `samtools` to compare output) How large is the timestamp difference?

**Comment by yoonkihoon** [comment]
I found that those bam and bam.idx files with timestamp issue actually had segmentation fault in markdup. I don't have any output reported with timestamp issue, but I will post them timestamp difference when I get one. I am pretty sure it will happen again. 

"finding positions of the duplicate reads in the file...
  sorted 111158757 end pairs
     and 3147397 single ends (among them 0 unmatched pairs)
  collecting indices of duplicate reads...   done in 18602 ms
  found 4948207 duplicates
collected list of positions in 3 min 55 sec
removing duplicates...
/cm/local/apps/torque/var/spool/mom_priv/jobs/28757.master.cm.cluster.SC: line 29: 113798 Segmentation fault      sambamba markdup -t 13 --remove-duplicates --tmpdir=/path/to/temp /path/to/input.sorted.bam /path/to/output.sorted.nodup.bam"

**Comment by yy1iang** [comment]
> Well, all file handling happens in the main thread, so I don't see these two issues as linked. Do region queries operate properly with the generated index? Does `samtools idxstats` give reasonable values? (reindex with `samtools` to compare output) How large is the timestamp difference?

```
-rw-r--r-- 1 yanyang domestic 452947402 2026-02-25 16:37:17.470701272 +0000 RJ_28.markdup.sorted.mapq30.bam
-rw-r--r-- 1 yanyang domestic 2143624 2026-02-25 16:37:17.062704658 +0000 RJ_28.markdup.sorted.mapq30.bam.bai
```

Difference in approximately .5 sec.
