### ISSUE TITLE
error：tar jxvf sambamba_v0.6.1_linux.tar.bz2  

### ISSUE THREAD

**Issue by Maple-Wang** [lomereiter/sambamba#213]
[nsfc2015_376@ln8%tianhe2-E SAMBAMBA]$ ls
sambamba_v0.6.1_linux.tar.bz2
[nsfc2015_376@ln8%tianhe2-E SAMBAMBA]$ tar jxvf sambamba_v0.6.1_linux.tar.bz2 
sambamba_v0.6.1
[nsfc2015_376@ln8%tianhe2-E SAMBAMBA]$ cd sambamba_v0.6.1
-bash: cd: sambamba_v0.6.1: Not a directory
[nsfc2015_376@ln8%tianhe2-E SAMBAMBA]$ 
[nsfc2015_376@ln8%tianhe2-E SAMBAMBA]$ 
[nsfc2015_376@ln8%tianhe2-E SAMBAMBA]$

**Comment by lomereiter** [comment]
It's indeed not a directory, but rather an executable, please use `chmod +x sambamba_v0.6.1` to set the right flags (I'm sorry for not doing so before archiving it).

**Comment by Maple-Wang** [comment]
thanks
