### ISSUE TITLE
sambamba mpileup hangs

### ISSUE THREAD

**Issue by nosepy** [lomereiter/sambamba#214]
When I run sambamba mpileup on a specific bam file without an input bed file with t 1 it finishes successfully.

sambamba mpileup -o RUN-xx_CellLine1_S41_L001_1-ready.mpileup_t1 -t 1 RUN-xx_CellLine1_S41_L001_1-ready.bam --samtools -A -B -Q 0 -d 1000000000 -f /opt/bcbio/data/genomes/Hsapiens/hg19/seq/hg19.fa

When increasing the number of threads to more than one the command hangs after some processing. In the temporary directory in /tmp I have seen, that one of the generated bed files is empty. In the mpileup generated with a single thread I see that some reads map to 4 unplaced contigs. This could be a hint to the problem. 

For more than 30 other BAM files the parallel processing with more than one thread is successful on the same machine. The problem is specific to the BAM which is attached and occurs with sambamba v.0.6.1 and also an earlier version. The analysis was done with hg19. As the mpileup runs successful on a single thread a problem with the BAM can be excluded.

When I use an input bed file containing the standard chromosomes 1-22,X,Y in the sambamba command the parallel run on the problematic bam is also successful.

Thank you for your time and effort.

Cheers,

Johannes

bam: (~26 MB)
    https://www.dropbox.com/s/xqqlpc5yqlnh2su/RUN-xx_CellLine1_S41_L001_1-ready.bam?dl=0
bai: (~1.5 MB)
    https://www.dropbox.com/s/pi8d9d4tm40s9up/RUN-xx_CellLine1_S41_L001_1-ready.bai?dl=0

**Comment by lomereiter** [comment]
Thanks for providing the test data, it turned out that I used outdated `lz4` library for compression, and it segfaulted on a certain input. Simply updating it solved the issue.

**Comment by nosepy** [comment]
Hi,

Thanks a lot for the quick correction.

Cheers,
Johannes
