### ISSUE TITLE
sambamba sort error when there's little memory and lots of I/O

### ISSUE THREAD

**Issue by diehlsa** [lomereiter/sambamba#218]
Hello,

I'm using sambamba as part of the bcbio-nextgen pipeline framework and I encountered some issue with the sort command. Specifically the error is:

`sambamba-sort: Unable to write to stream`

There is enough space on the disk and enough free memory. I figured out that the error only occurs if I give 1G or less memory with the `-m` parameter. My input file is almost 90 GB big and due to how the pipeline runs it, there is some other I/O at the same time. From looking at the resource monitoring of the node, it looks like sambamba starts swapping before it crashes. There are no other errors on the system or filesystem side. My HPC experts think the following is happening: 

> The tool buffered writes waiting for them to complete until it ran out of memory and crashed.

**Comment by lomereiter** [comment]
Hi,

I suspect it's just too high I/O load because of many temporary files—I'd estimate ~200 opened files at the same time with 1G of memory allocated. If possible, try to use temporary directory on the local disk.

**Comment by diehlsa** [comment]
It's actually close to 400 temporary files. I agree that it's due to too much I/O. Unfortunately our machines have very little space on the local disk. I'm using our high-performance Lustre filesystem for this. However, since there are no errors on the Lustre side, it seems like it's not the FS crashing.
