### ISSUE TITLE
json output not valid json for multiple reads

### ISSUE THREAD

**Issue by kiramt** [lomereiter/sambamba#220]
Using the --format=json option gives valid json output for each read, but the combination is not (according to e.g. https://jsonformatter.curiousconcept.com). It just needs to be enclosed in [] and commas between each read to make it valid.

**Comment by lomereiter** [comment]
That's technically true, but I don't see a point of producing an array with millions of elements that would require downstream scripts to use streaming json parsers.

**Comment by kiramt** [comment]
Maybe clarify the docs then? It isn’t clear that sambamba won’t actually produce valid json output.

I chose to use sambamba because I want to read (some, not millions of) reads into a pandas dataframe and since sambamba seemed to produce json output and pandas reads json into a dataframe this seemed like a good plan!

**Comment by lomereiter** [comment]
Thanks for the suggestion, I fixed the docs and added [jq](https://stedolan.github.io/jq/) as recommendation.
