### ISSUE TITLE
depth tool ignoring last base in interval

### ISSUE THREAD

**Issue by mbootwalla** [lomereiter/sambamba#221]
Hi Artem,

I ran sambamba depth in base mode and provided a standard bed file (0-based start and 1-based end from UCSC genome browser) as the regions file. I noticed that sambamba depth was calculating the depth at all bases (including the starting base) but was ignoring the end base. I assumed that the tool would deal with a bed file correctly i.e. it would start calculating the coverage from **start + 1** base all the way to the **end** base but it does not seem to be doing so. I tried samtools depth with the -b option and the same regions bed file and it works correctly but it is a lot slower than the sambamba depth tool. Is there a particular format of the region file that the tool expects? Can you kindly look into this and let me know if there is some modification that I should do to my regions file to get the tool to work correctly?

Here is the command I used to generate the per base coverage:

`sambamba depth base -t 12 -F '' -z -L BED_FILE BAM_FILE`

And here is an excerpt of the bed file that I used:

1       877933  878443  SAMD11_cds10    +       510     SAMD11
1       878627  878762  SAMD11_cds11    +       135     SAMD11
1       879072  879193  SAMD11_cds12    +       121     SAMD11
1       879282  879538  SAMD11_cds13    +       256     SAMD11
1       880068  880185  NOC2L_cds1      -       117     NOC2L
1       880431  880531  NOC2L_cds2      -       100     NOC2L
1       880892  881038  NOC2L_cds3      -       146     NOC2L

Thank You,

Moiz

**Comment by lomereiter** [comment]
Hi Moiz,

That's a documentation issue. I checked, and `samtools depth` uses 1-based indexing in output, while `sambamba depth base` prints 0-based positions so that the range is [start, end - 1]

**Comment by mbootwalla** [comment]
Thank you Artem. This makes sense now.

Regards,

Moiz

**Comment by duartemolha** [comment]
should a 0 base posions reporting be start+1 to end? 

I.e if my snp is at position 100 on chr1 a bed file (0 base) would report that coordinate as chr1 99 100

if you report star , end-1 then you would be reporting the coverage on position 99  which is not correct according to input

**Comment by pjotrp** [comment]
@duartemolha I am not sure what you are asking here. If you can provide a concrete example I may be able to help.
