### ISSUE TITLE
Random segfaults with sambamba 0.6.1 bioconda release

### ISSUE THREAD

**Issue by schelhorn** [lomereiter/sambamba#223]
Hello, I get random segfaults of sambamba 0.6.1 from the current bioconda release in bcbio. It's occurring when doing depth calling on WGS BAMs and a BED file with merged exon regions (60340 regions). The BED file validates fine using `bedops`. The BAM file also validates using `samtools quickcheck`. Funny thing is, that it's not really reproducible but occurs more or less randomly for different samples. 

Exemplary command line call:

```/USERNAME/bcbio/lib/anaconda/bin/sambamba depth region -t 4 -L /USERNAME/bcbio/regions/bcbio_reference_exons_GRCh37_bed4_merged_10kbp.bed -F "not unmapped" -T 10 -T 20 -T 30 -T 40 -T 50 -T 60 -T 70 -T 80 -T 90 -T 100 /USERNAME/BCBIOPROJECT/align/SAMPLENAME/SAMPLENAME-sort.bam -o /USERNAME/BCBIOPROJECT/qc/SAMPLENAME/coverage/tx/tmpIpgrzS/SAMPLENAME_priority_total_coverage.bed```

resulting in 

```/bin/bash: line 1: 123147 Segmentation fault      (core dumped)```, which is a segmentation fault in sambamba after a couple of references have been processed.

Applying gdb on the sambamba core dump results in the following:
```
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /USERNAME/bcbio/lib/anaconda/bin/sambamba...done.
[New LWP 123153]
[New LWP 123147]
[New LWP 123150]
[New LWP 123151]
[New LWP 123152]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/USERNAME/bcbio/lib/anaconda/bin/sambamba depth base -t 4 -L .
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00002b1364637409 in __memmove_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:201
201     ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
[Current thread is 1 (Thread 0x2b13650b7700 (LWP 123153))]
```
I am running Ubuntu 15.10; RAM (260GB) and HD (sufficiently) are not the issues here. 

`ulimit -a` says:

```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 983279
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 10000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 983279
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

`cat /proc/cpuinfo` says (one of 32 cores):

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
stepping        : 2
microcode       : 0x2d
cpu MHz         : 2091.656
cache size      : 30720 KB
physical id     : 0
siblings        : 18
core id         : 0
cpu cores       : 9
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq monitor est ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm ida fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
bugs            :
bogomips        : 4800.09
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```
Any idea on how to proceed?

**Comment by schelhorn** [comment]
Update: I am trying to recompile from source an use the debugging make target `sambamba-ldmd2-debug`.

**Comment by lomereiter** [comment]
Hi, please run it under GDB and add the backtrace to the report.

**Comment by schelhorn** [comment]
When using the debugging binary from the repo state from seven days ago, depth calling on all my samples completed successfully without segfault. Assuming that the debugging binary does not catch and handle errors that the production version does not, it seems as if the bug is now fixed. Could you please commit the 0.6.3. release to bioconda so that I can test the release?

**Comment by lomereiter** [comment]
Please thoroughly test the binary from Github releases locally before jumping to conclusions. Behavior of production version might differ for various reasons such as compiler (mis-)optimizations.

**Comment by wresch** [comment]
I wanted to report that we may be experiencing the same issue (non-deterministic segfaults) with sambamba 0.6.3 that is installed as part of bcbio (i.e. bioconda). And since it's bcbio-nextgen, it's kind of hard to debug. Relevant error:

```
/bin/bash: line 1: 34037 Segmentation fault      /fdb/bcbio-nextgen/current/anaconda/bin/sambamba view -f bam -L /path/to/sorted.bam   
     34038 Done                    | /fdb/bcbio-nextgen/current/anaconda/bin/bedtools intersect -abam - -b //path/to/blocks.bed -f 1.0 -nonamecheck >  /path/to/sort-noanalysis-prep.bam                        
' returned non-zero exit status 139
```

I was going to recompile from source but since I'm on CentOS 6.6 i can't use the binary ldmd2 (glibc too old) at which point recompiling becomes a chore.

**Comment by chapmanb** [comment]
I'm not sure about the underlying sambamba cause here but if you don't need realignment and recalibration in bcbio you could avoid this problem with your analysis by adding:
```
realign: false
recalibrate: false
```
to your config and it shouldn't need to do this specific BAM processing step. Sorry to not have an actual answer but hope that helps.

**Comment by pfpjs** [comment]
Just chiming in to report the same kind of non-deterministic segmentation fault in sambamba 0.6.3 as a part of bcbio-nextgen:

```
[2016-08-04T12:59Z] Processing reference #1 (1)
[2016-08-04T12:59Z] Processing reference #2 (2)
[2016-08-04T13:00Z] Processing reference #3 (3)
[2016-08-04T13:00Z] Processing reference #4 (4)
[2016-08-04T13:00Z] Processing reference #5 (5)
[2016-08-04T13:00Z] Processing reference #6 (6)
[2016-08-04T13:01Z] Processing reference #7 (7)
[2016-08-04T13:01Z] Processing reference #8 (8)
[2016-08-04T13:01Z] Processing reference #9 (9)
[2016-08-04T13:01Z] Processing reference #10 (10)
[2016-08-04T13:01Z] Processing reference #11 (11)
[2016-08-04T13:02Z] Processing reference #12 (12)
[2016-08-04T13:02Z] Processing reference #13 (13)
[2016-08-04T13:02Z] Processing reference #14 (14)
[2016-08-04T13:02Z] /bin/bash: line 1:  1420 Segmentation fault      (core dumped) /path/to/bcbio/anaconda/bin/sambamba depth region -F "not unmapped" -t 17 -C 1000 -T 1 -T 5 -T 10 -T 20 -T 40 -T 50 -T 60 -T 70 -T 80 -T 100 -L /path/to/coverage.bed /path/to/sorted.bam
      1421 Done                    | sed 's/# chrom/chrom/' > tx/tmpUMPyAj/coverage.bed
' returned non-zero exit status 139
```

Running the same sambamba command again (by restarting the analysis, bcbio picks up where it stopped before) finishes successfully:

```
[2016-08-04T13:07Z] Processing reference #1 (1)
[2016-08-04T13:07Z] Processing reference #2 (2)
[2016-08-04T13:07Z] Processing reference #3 (3)
[2016-08-04T13:08Z] Processing reference #4 (4)
[2016-08-04T13:08Z] Processing reference #5 (5)
[2016-08-04T13:08Z] Processing reference #6 (6)
[2016-08-04T13:08Z] Processing reference #7 (7)
[2016-08-04T13:08Z] Processing reference #8 (8)
[2016-08-04T13:09Z] Processing reference #9 (9)
[2016-08-04T13:09Z] Processing reference #10 (10)
[2016-08-04T13:09Z] Processing reference #11 (11)
[2016-08-04T13:09Z] Processing reference #12 (12)
[2016-08-04T13:09Z] Processing reference #13 (13)
[2016-08-04T13:09Z] Processing reference #14 (14)
[2016-08-04T13:10Z] Processing reference #15 (15)
[2016-08-04T13:10Z] Processing reference #16 (16)
[2016-08-04T13:10Z] Processing reference #17 (17)
[2016-08-04T13:10Z] Processing reference #18 (18)
[2016-08-04T13:10Z] Processing reference #19 (19)
[2016-08-04T13:11Z] Processing reference #20 (20)
[2016-08-04T13:11Z] Processing reference #21 (21)
[2016-08-04T13:11Z] Processing reference #22 (22)
[2016-08-04T13:11Z] Processing reference #23 (X)
[2016-08-04T13:11Z] Processing reference #24 (Y)
```

**Comment by RoanKanninga** [comment]
I'm having the same issue as user pfpjs above
We are using also v0.6.3 

finding positions of the duplicate reads in the file...
[========================================================================]
  sorted 57411864 end pairs
     and 188183 single ends (among them 0 unmatched pairs)
  collecting indices of duplicate reads...   done in 11600 ms
  found 3322636 duplicates
collected list of positions in 8 min 34 sec
marking duplicates...
[>                                                                             ]/var/spool/slurmd/job25892/slurm_script: line 180:   648 Segmentation fault      (core dumped) /path/to/sambamba_v0.6.3 markdup --nthreads=4 --overflow-list-size 1000000 --hash-table-size 1000000 -p ${myBam} ${outputBam}
finding positions of the duplicate reads in the file...

After rerunning the same sample everything is just fine :/

**Comment by sicotte** [comment]
I also encounter errors with 0.6.3 in 8 out of 9 files I tried.
/projects/bsi/pharmacogenetics/s114526.promote/tools/QC/src/sambamba_v0.6.3 sort -n -m 60000000000 -p -t 1 -o $SORTEDBAM $BAM

Note that I am sorting an RNASeq BAM file with multiple alignment for the same reads, if that helps.

**Comment by roys911** [comment]
I see the same error with 0.6.3 (installed from bioconda) in a small subset of my DNAseq bam files. Rerunning the command again, as was suggested, does not help. Below is the command and output. The input bam was sorted using sambamba.

`sambamba markdup -t 30 -p sample.sorted.bam sample.sorted.dedup.bam

finding positions of the duplicate reads in the file...
[==============================================================================]+
  sorted 38108813 end pairs
     and 261708 single ends (among them 0 unmatched pairs)
  collecting indices of duplicate reads...   done in 5244 ms
  found 11507547 duplicates
collected list of positions in 2 min 25 sec
marking duplicates...
[==>                                                                           ]Segmentation fault`

**Comment by lomereiter** [comment]
Hi @roys911, is the error reproducible with the latest version (0.6.4)? It is not yet on bioconda channel, but available on the github [releases](https://github.com/lomereiter/sambamba/releases) page.

**Comment by roys911** [comment]
Hi @lomereiter, I have not tried that. I will give it a try. 
Thanks!

**Comment by roys911** [comment]
I tried v0.6.5 from your github release page... It works like a CHARM!!!  
Thanks a ton!

**Comment by lomereiter** [comment]
Thanks for testing, 0.6.5 will be on bioconda ASAP.
