### ISSUE TITLE
feature request: retain additional columns, sambamba depth base?

### ISSUE THREAD

**Issue by parlar** [lomereiter/sambamba#227]
Hi! 

If you're interested in feature requests... ?

In addition to my earlier suggestion to provide bedgraph output, 
a neat thing would be if info in additional columns could be retained in the output from regions.bed if used. Possible by the use of another annotate flag?

**Comment by lomereiter** [comment]
It's unclear what's to be printed if a base is present in multiple BED regions.

**Comment by parlar** [comment]
Thats true!
