### ISSUE TITLE
Ignores Chr6?

### ISSUE THREAD

**Issue by mattdmem** [lomereiter/sambamba#232]
sambamba depth base -q29 -m --min-coverage=0 -L

Weird problem:
I have a bed with multiple regions, some of which are on chr6, they are uncovered.  Sambamba doesn't report on these at all.  If you take out all other regions BUT chr6 it works fine!

Any ideas?

I'm thinking because the whole region and not just a couple of bases on chr6 it is triggering a bug?

Thanks!

**Comment by mattdmem** [comment]
Just to follow up depth region with just these chr6 regions output nothing, but they are outputted fine with coverage 0 if you use the total bed file.

**Comment by mattdmem** [comment]
Any ETA on a fix for this?

**Comment by lomereiter** [comment]
Hi, if you provide a test case, I'd say one week.

**Comment by mattdmem** [comment]
What do you need? Mini Bam file and bed files?

**Comment by lomereiter** [comment]
Ideally yes. If you can't minify it, no problem, just send as it is.

**Comment by mattdmem** [comment]
Ok - I'm going to actually get round to giving you an example at some point :)

**Comment by mattdmem** [comment]
our data is clinical so I have to do some wrangling to make it shareable or make a simulated example

**Comment by lomereiter** [comment]
Great, thanks. There's a script in the repository that could be useful: https://github.com/lomereiter/sambamba/blob/master/randomize_bases.d
