### ISSUE TITLE
Failing tests on a big endian platform

### ISSUE THREAD

**Issue by IvantheDugtrio** [lomereiter/sambamba#235]
I got the following errors after running tests on my sambamba build.

As a note this was performed on CentOS 7.2 ppc64 on a POWER7 server. 

This was from rdmd -unittest -d test/unittests.d
[BioD-bugs.txt](https://github.com/lomereiter/sambamba/files/364492/BioD-bugs.txt)

And this was from sh .test_suite.sh
[sambamba-bugs.txt](https://github.com/lomereiter/sambamba/files/364491/sambamba-bugs.txt)

**Comment by lomereiter** [comment]
Hi, I've pushed some fixes, please re-run the tests and report if anything still fails.

**Comment by IvantheDugtrio** [comment]
Some new errors after the patches
[BioD-bugs.txt](https://github.com/lomereiter/sambamba/files/370592/BioD-bugs.txt)
[sambamba-bugs.txt](https://github.com/lomereiter/sambamba/files/370594/sambamba-bugs.txt)

**Comment by lomereiter** [comment]
Sorry but I have nothing big-endian around, if anyone can recommend where or how I could test builds, I'd appreciate that a lot. Fixing endian-related bugs by sending emails back and forth is not an option.

**Comment by IvantheDugtrio** [comment]
What if I gave you SSH access to my server?

**Comment by lomereiter** [comment]
@IvantheDugtrio yes, that would be great!

**Comment by IvantheDugtrio** [comment]
Great I'll contact my IT department to get the port opened up. 

So I've set up a new CentOS VM and am having trouble just building the latest version of LDC. I've tried different versions of LLVM and CMake and it's still not working.

**Comment by IvantheDugtrio** [comment]
So it looks like my company's IT won't allow access to non-employees. 

Good news is this seems to be an issue with LDC so I would wait for that to get sorted out first. 

I'll close this for now until LDC sorts their part out.
