### ISSUE TITLE
differences between 0.5.5 and 0.6.1 -> 0.5.5 is much faster!

### ISSUE THREAD

**Issue by RichardCorbett** [lomereiter/sambamba#239]
Hi,

We're still enjoying using the sambamba tool that you wrote.  I'm impressed how you made it work so quickly.

We did a lot of testing with 0.5.5 and recently switched to 0.6.1.    In the release notes you mentioned introducing external sort, which I expect to make things a little slower at the cost of reducing the RAM requirement.   I just wanted to make sure that the following difference makes sense to you.

Using 0.5.5:

```
sambamba_v0.5.5 markdup --hash-table-size 5000000 --overflow-list-size 5000000 --tmpdir /var/tmp --io-buffer-size 1024 A61236_4_lanes55.bam A61236_4_lanes_dupsFlagged55.bam
real    66m27.625s
user    670m13.528s
sys 176m11.209s

```

Using 0.6.1:

```
sambamba_v0.6.1 markdup --hash-table-size 5000000 --overflow-list-size 5000000 --tmpdir /var/tmp --io-buffer-size 1024 A61236_4_lanes.bam A61236_4_lanes_dupsFlagged.bam
finding positions of the duplicate reads in the file...
  sorted 603635386 end pairs
     and 6111173 single ends (among them 866 unmatched pairs)
  collecting indices of duplicate reads...   done in 129928 ms
  found 125498017 duplicates
collected list of positions in 92 min 31 sec
marking duplicates...
total time elapsed: 195 min 36 sec

real    195m39.576s
user    878m53.623s
sys 13m26.409s

```

Since there is such a difference between versions I guess I wanted to make sure there are no critical fixes to sort/markdup/merge/flagstat that would make 0.5.5 obsolete.

**Comment by lomereiter** [comment]
Hi, thanks for the report.

The user times look comparable, so it's mostly the degree of parallelism which is affected.
The new serial steps introduced are mostly dumping to disk and reading back, so having fast temporary storage is quite helpful. What could be done here is:
* special-casing one-file scenario to not dump anything to disk
* dedicated threads for reading/writing but then the temporary file sizes would need to be cut at least in half (with the same memory usage)

**Comment by RichardCorbett** [comment]
Thanks Artem,
Just to double check, since we have oodles of RAM to work with (multiple Terabytes) we'll probably stick with 0.5.5. Do you know of any reason we shouldn't keep 0.5.5?   It looks as though there have been no bugfixes to sort/merge/dupmark/flagstat since 0.5.5, but I want to double check.

**Comment by lomereiter** [comment]
Hi Richard,
There actually have been a few important fixes in the mean time:
* Fix in indexing routine for reads that span more than one block (i.e. > 65KB in size), critical for PacBio data https://github.com/lomereiter/sambamba/commit/7f7e7a90a1eb789883a387f1897ea7195b969f28
* Updated `lz4` library (it used to contain a bug leading to segfaults) https://github.com/lomereiter/sambamba/commit/742949ae22a465e304a2a16ee623717f736739b6

Feel free to cherry-pick any of these commits if you encounter issues with 0.5.5

**Comment by pjotrp** [comment]
Following up in https://github.com/lomereiter/sambamba/issues/277
