### ISSUE TITLE
mpileup - sambamba result differs from samtools result

### ISSUE THREAD

**Issue by spabinger** [lomereiter/sambamba#244]
Hi,

I tested several files using sambamba mpileup (v0.6.3) and compared the output to samtools mpileup (v1.2). Unfortunately, I noticed that the two output files differ, sambamba output **is missing several lines**.

You can find a test file at:
https://dl.dropboxusercontent.com/u/14071835/test_file.bam

I executed the following script:
## Samtools
samtools mpileup -o samtools.mpileup -A -B -Q 0 -d 1000000000 -f hg19.fa test_file.bam

## Sambamba
sambamba mpileup -o sambamba.mpileup -t 32 test_file.bam --samtools -A -B -Q 0 -d 1000000000 -f hg19.fa

## Show diff
diff samtools.mpileup sambamba.mpileup

Best wishes,
Stephan

**Comment by lomereiter** [comment]
Thanks, confirmed, indeed a few bases at the end of chr2 are missing because of buggy BED calculation (https://github.com/biod/BioD/blob/8a18c41b19c42589205945e9d18d1c4f5184505b/bio/bam/pileup.d#L901-L903)

**Comment by spabinger** [comment]
Hi Artem,

thanks for the fast reply. Do you think you will be able to release a new version in the near future?

Best wishes,
Stephan
