### ISSUE TITLE
markdup wrong BGZF magic

### ISSUE THREAD

**Issue by jdmontenegro** [lomereiter/sambamba#255]
Hi,
I am new working with sambamba and I find it extremely useful. I just ran into a problem I cannot work around with markdup. After sorting and filtering a bam file with sambamba:
    $> sambamba sort -t 15 --tmpdir=TMP -o out.sorted.bam in.bam
    $> sambamba view -h -t 15 -F "mapping_quality>=20 and proper_pair"  -o out.sorted.f.bam
    out.sorted.bam

To get sambamba running I had to increase the stack size limit to 64M with:
    ulimit -s 65556
to avoid a seg fault error on the view and sort commands. The error still appears, but the files are complete, have no errors and can be handled by other tools like samtools without warnings or complains.

Then I try to remove duplicates from the last output:
    $> sambamba markdup -r -t 15 --tmpdir=TMP out.sorted.f.bam out.sorted.fd.bam
but get this error:
    sambamba-markdup: Error reading BGZF block starting from offset 0: wrong BGZF magic

And cannot make it work. I have not found any thread related to this problem so I have no idea how to work around it. I have been able to use samtools rmdup on that file, but I would like to use only one tool for this and sambamba looks better.

Regards,

**Comment by pjotrp** [comment]
Usually the BGZF error is because a command is trying to read a non-BAM file (say SAM).

**Comment by jdmontenegro** [comment]
well, in this case it was a complete bam file that was produced by
samtools. In the end I had to use samtools to sort it out.

Sambamba offers many improvements, unfortunately I was not able to use it
in my project.

regards,

Juan Montenegro

2017-02-24 3:43 GMT+10:00 Pjotr Prins <notifications@github.com>:

**Comment by pjotrp** [comment]
The help page of view says:

```
Usage: sambamba-view [options] <input.bam | input.sam> [region1 [...]]

Options: -F, --filter=FILTER
                    set custom filter for alignments
         --num-filter=NUMFILTER
                    filter flag bits; 'i1/i2' corresponds to -f i1 -F i2 samtools arguments;
                    either of the numbers can be omitted
         -f, --format=sam|bam|cram|json
                    specify which format to use for output (default is SAM)
```

Going from above instructions you were feeding `sambamba markdup` a SAM file, not a BAM file. The preceding command should have been

```sh
sambamba view --format=bam -h -t 15 -F "mapping_quality>=20 and proper_pair" -o out.sorted.f.bam
out.sorted.bam
```
