### ISSUE TITLE
Is sambamba 0.6.4 the correct release?

### ISSUE THREAD

**Issue by ernfrid** [lomereiter/sambamba#256]
@lomereiter - I just noticed that the binaries for 0.6.4 are self reporting as 0.6.3 and it also looks like the new functionality for retaining the AH tag in the header isn't working or isn't present. Is there any way to tell if the binary that's present currently for 0.6.4 is a mislabeled 0.6.3 or if the newest version has a bug regarding AH handling?

Thanks in advance!

**Comment by lomereiter** [comment]
Thanks for spotting this, it was indeed a mislabeled 0.6.3 (judging from the executable size).
I re-uploaded the binaries.

**Comment by ernfrid** [comment]
Thank you for fixing it so quickly! I've downloaded the new binary and verified that the AH tag is now properly handled and that the version string now reports 0.6.4.

Thank you for your work on sambamba. We use it throughout our pipeline and it is invaluable to have such an efficient tool to rely upon.
