### ISSUE TITLE
max number of input files during merge?

### ISSUE THREAD

**Issue by RichardCorbett** [lomereiter/sambamba#263]
Hi Artem,
 We're planning to use sambamba in a project where we'll routinely merge many tiny bam files  (hundreds) into 1 bam file.  Each resulting BAM will be about the dize of 2-3 HiSeqX lanes.

Are you aware of any limit on the number of BAM files going in to a merge?

thanks,
RIchard

**Comment by lomereiter** [comment]
Hi Richard,
You might have to increase the system limit on the number of open files but otherwise it should work fine.
http://stackoverflow.com/questions/34588/how-do-i-change-the-number-of-open-files-limit-in-linux
