### ISSUE TITLE
Samtools style filtering syntax

### ISSUE THREAD

**Issue by edawson** [lomereiter/sambamba#264]
Is there a way to use samtools style (i.e. decimal) filter expressions with sambamba? I expected that it would be supported (given that the human-readable version is surely built on top of it). I'm having to use massive command lines to do filtering and would rather use a four-digit decimal.

If you could point me towards the relevant manual page I've missed or let me know if it's possible that'd be great. The sort+filter operation is fantastic, and I'd love to keep using it, but without a flag->filter converter or a way to just use the flag I think I'll have to switch to samtools for this project.

**Comment by lomereiter** [comment]
Hi, this functionality was indeed missing. I've just added a new option `--num-filter`, which should be provided a string such as `96`, `/4` or `80/4` with meaning `<-f samtools flag>/<-F samtools flag>`.
