### ISSUE TITLE
Merging pre-sorted BAM files: is sorting merged bam needed again?

### ISSUE THREAD

**Issue by terrymun** [lomereiter/sambamba#266]
Thanks for the amazing tool! I have a question and it isn't immediately clear from the documentation for `sambamba merge`:

> `sambamba merge` is used for merging several sorted BAM files into one. The sorting order of all the files must be the same, and it is maintained in the output file.

Does that mean that if I am using a list of sorted BAM files for merging using sambamba, I do not have to re-sort the merged BAM file?

**Comment by lomereiter** [comment]
Yep, that's right. FYI, in CS jargon 'merge' almost always refers to the https://en.wikipedia.org/wiki/Merge_algorithm, in this case K-way merging.

**Comment by terrymun** [comment]
Thanks for the clarification :+1
