### ISSUE TITLE
Many deprecation warnings with ldc-1.0.0 and later

### ISSUE THREAD

**Issue by pjotrp** [lomereiter/sambamba#269]
There are many warnings that can (easily) be fixed: https://travis-ci.org/lomereiter/sambamba/builds/200621264

**Comment by lomereiter** [comment]
I believe are in fact already fixed in BioD master (by other people), but it started using `undead` for deprecated `std.stream`, so the build process needs to be updated together with the submodule.

**Comment by pjotrp** [comment]
So we are using undeaD now, but there still is a range of warnings. I'll fix them when I feel like doing that.
