### ISSUE TITLE
No 'mpileup' documentation on main docs site

### ISSUE THREAD

**Issue by tseemann** [lomereiter/sambamba#272]
There is no `mpileup` documentation tab at http://lomereiter.github.io/sambamba/

![image](https://cloud.githubusercontent.com/assets/453972/23195354/022ebd06-f907-11e6-96eb-642a2cd860a8.png)

**Comment by pjotrp** [comment]
Hi @tseemann mpileup is essentially a parallelization wrapper over samtools. Probably better ways to achieve the same exist. But maybe we'll add a tab one day ;)
