### ISSUE TITLE
bin in read set incorrectly -- sambamba markdup

### ISSUE THREAD

**Issue by avilella** [lomereiter/sambamba#275]
Ran sambamba v0.5.5 on a bam file aligned with bwa mem. It comes up with a binning error:

```
sambamba-markdup: Bin in read with name 'NB501627:53:HYCCNBGXY:3:12511:23039:11709' is set incorrectly (1648 instead of expected 13186)
```

Any way this can be fixed/ignored during sambamba markdup? Before?

**Comment by lomereiter** [comment]
Hi, this should be fixed in versions ≥ 0.5.9, please upgrade.
