### ISSUE TITLE
Depth for amplicon sequence

### ISSUE THREAD

**Issue by tiehan** [lomereiter/sambamba#289]
Can sambamba depth calculate the PCR based amplicon's (overlap amplicons) depth?
I have  many overlap amplicons.
Through the bam file , I can get the pair reads start and end . The pair reads' start and end is completely match to one of amplicons. I want get every amplicon's real depth to evaluate every amplicon's performance.
Can sambamba do this ?

**Comment by lomereiter** [comment]
No, you'll have to write some code on your own, as I see has been advised already by CNVKit people.

**Comment by tiehan** [comment]
OK，Thanks
