### ISSUE TITLE
Sambamba equivalent of bedcov?

### ISSUE THREAD

**Issue by abalter** [lomereiter/sambamba#292]
Is there an equivalent?

**Comment by lomereiter** [comment]
There's no exact equivalent, but you can use 
`sambamba depth region -L <bed file> <bam file> -q <min base quality> -F <read filter>`
and then use `meanCoverage` column to deduce the number of bases, multiplying it by the region length.

**Comment by abalter** [comment]
Is there documentation on the `depth` method? Can it take multiple bam files?

**Comment by lomereiter** [comment]
You can see short help by running it without arguments. Multiple BAM are supported but keep in mind that `sambamba` relies only on read groups for per-sample statistics, not on filenames.

**Comment by abalter** [comment]
Yup. I just did `sambamba depth -h` :)

**Comment by abalter** [comment]
What is `meanCoverage`

**Comment by lomereiter** [comment]
It's what's expected from the name: number of bases in the region that come from the reads satisfying the filter conditions and that have base call quality at least `-q`
