### ISSUE TITLE
Sambamba index file

### ISSUE THREAD

**Issue by Virome1** [lomereiter/sambamba#298]
I'm not sure if this question should be put on here. 

I am piping from BWA to sambamba to sort my bam files. This is the code:
`for filename in ./seqtk_2/subsample_1/*_1.fq.gz;
do file=`echo $filename|sed 's/_1.fq.gz//'`;
filenopath=`basename $file`;
outputpath=./BWA/seqtk_2/subsample_1;
bwa mem -v 3 ./combine_reference.fa.gz ${file}_1.fq.gz ${file}_2.fq.gz | sambamba view -S -f bam /dev/stdin | sambamba sort /dev/stdin -o ${outputpath}/sorted_${filenopath}_BWA.bam;
done`

The code is working (thats not the problem). However, it is also creating bai files with the bam file.

I thought bai files were only possible from sambamba index? They appear to be valid bai files. Just confused

**Comment by lomereiter** [comment]
Hi, anything that writes coordinate-sorted files to disk, also writes the index file at the end.
