### ISSUE TITLE
sambamba-markdup: Conversion positive overflow

### ISSUE THREAD

**Issue by pwwang** [lomereiter/sambamba#300]
* version of sambamba
`sambamba 0.6.6`

* the command line or bash script used (feel free to shorten paths and filenames)
`sambamba markdup "testPE1.bam" "testPE2.bam"`
The output:
`finding positions of the duplicate reads in the file...`
`sambamba-markdup: Conversion positive overflow`

* whenever possible, a set of BAM/BED files to reproduce the issue
  The input bam file was converted from a test sam file available here: https://gist.githubusercontent.com/pwwang/6c027d43eeb0af9b4d203bd7470b4b89/raw/7f5b084c14da76b13d8d70b119ca617c19d20dae/testPE1.sam, which was generated by `simulate.pl` by bowtie2's Lambda phage example.

**Comment by LocutusOfBorg** [comment]
Hello, the fix in 0583f49 regressed i386 builds, the assert 36u == 40u is now false there... any idea?

**Comment by pjotrp** [comment]
Interesting find. Looks like something is doing the wrong thing here. Are you building the latest release?

**Comment by LocutusOfBorg** [comment]
yes, 0.6.7 version here
https://packages.qa.debian.org/s/sambamba.html
https://buildd.debian.org/status/fetch.php?pkg=sambamba&arch=i386&ver=0.6.7-1&stamp=1521544853&raw=0

**Comment by LocutusOfBorg** [comment]
in the meanwhile @tillea opened a new ticket #344, so better followup there
