### ISSUE TITLE
build fails with "module bitarray is in file 'undeaD/src/undead/bitarray.d' which cannot be read"

### ISSUE THREAD

**Issue by kortschak** [lomereiter/sambamba#305]
Attempting to build sambamba at sha 1e3feed174588359a6a558cdbac60bb0e721c0d8 fails with

```
ldmd2 @sambamba-ldmd-release.rsp
Error: module bitarray is in file 'undeaD/src/undead/bitarray.d' which cannot be read
import path[0] = /usr/include/d/ldc
import path[1] = /usr/include/d
import path[2] = BioD/
import path[3] = undeaD/src/
import path[4] = .
Makefile:44: recipe for target 'sambamba-ldmd2-64' failed
make: *** [sambamba-ldmd2-64] Error 1
```

**Comment by lomereiter** [comment]
Hi Dan, you should run `git clone https://github.com/dlang/undeaD` prior to build.

**Comment by dannykwells** [comment]
I'm encountering the same problem as well, and I did follow the above instructions. Is there a directory where that needs to go?

This is what the Dockerfile looks like: 

 42 RUN git clone https://github.com/dlang/undeaD
 43 RUN chmod 777 undeaD
 44 RUN wget https://github.com/ldc-developers/ldc/releases/download/v0.17.1/ldc2-0.17.1-linux-x86_64.tar.xz && \
 45   tar xJf ldc2-0.17.1-linux-x86_64.tar.xz
 46
 47 ENV PATH=/undeaD/:/ldc2-0.17.1-linux-x86_64/bin/:$PATH
 48 ENV LIBRARY_PATH=/ldc2-0.17.1-linux-x86_64/lib/
 49
 50 RUN git clone --recursive https://github.com/lomereiter/sambamba.git && \
 51   cd sambamba; make sambamba-ldmd2-64

Any thoughts?

**Comment by lomereiter** [comment]
@dannykwells `undeaD` is supposed to be cloned into `sambamba/` directory and not separately, sorry if that's not clear from the README
