### ISSUE TITLE
install error in the make step

### ISSUE THREAD

**Issue by kumakiwami** [lomereiter/sambamba#310]
I try to install sambaed according to the  official suggested command, 
```bash
git clone --recursive https://github.com/lomereiter/sambamba.git
cd sambamba && make sambamba-ldmd2-64
```
then an error occurred in the make step, please see below,
```
./gen_ldc_version_info.py  > utils/ldc_version_info_.d
make: *** [ldc-version-info] Error 1
```

OS: ubuntu 14.04

**Comment by pjotrp** [comment]
We should tee this command. Check what is in utils/ldc_version_info_.d

**Comment by kumakiwami** [comment]
@pjotrp Thanks, it has been solved.
