### ISSUE TITLE
sambamba installation problem!

### ISSUE THREAD

**Issue by vd4mmind** [lomereiter/sambamba#316]
I am trying to use the latest sambamba by downloading it from the git however after installing the LDC I still have issues below is the $PATH and $LIBRARY_PATH information followed by the set of commands used for installing sambamba
command for downloading LDC

```
wget https://github.com/ldc-developers/ldc/releases/download/v0.17.5/ldc2-0.17.5-linux-x86_64.tar.xz
tar xJf ldc2-0.17.5-linux-x86_64.tar.xz
```
Then I set up the path and below are my $PATH and $LIBRARY_PATH , post that I tried to install sambamb as show below and I still get the error. 
```
echo $PATH
/marconi/home/userexternal/vdas0000/marconi/home/userexternal/vdas0000/ldc2-0.17.5-linux-x86_64/bin:/marconi_work/ELIX2_prj6/anaconda2/bin:/cineca/bin:/usr/lib64/qt-3.3/bin:/cineca/sysprod/pbs/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/marconi/home/userexternal/vdas0000/.local/bin:/marconi/home/userexternal/vdas0000/bin
[vdas0000@r000u07l02 ~]$ echo $LIBRARY_PATH
/marconi/home/userexternal/vdas0000/marconi/home/userexternal/vdas0000/ldc2-0.17.5-linux-x86_64/bin:/marconi_work/ELIX2_prj6/anaconda2/bin:/cineca/bin:/usr/lib64/qt-3.3/bin:/cineca/sysprod/pbs/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/marconi/home/userexternal/vdas0000/.local/bin:/marconi/home/userexternal/vdas0000/bin
[vdas0000@r000u07l02 ~]$ cd /marconi_work/ELIX2_prj6/tmpSoft/sambamba.latest/sambamba

git clone --recursive https://github.com/lomereiter/sambamba.git
cd sambamba
git clone https://github.com/dlang/undeaD
make sambamba-ldmd2-64
Error:
which: no ldmd2 in (/marconi/home/userexternal/vdas0000/marconi/home/userexternal/vdas0000/ldc2-0.17.5-linux-x86_64/bin:/marconi_work/ELIX2_prj6/anaconda2/bin:/cineca/bin:/usr/lib64/qt-3.3/bin:/cineca/sysprod/pbs/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/marconi/home/userexternal/vdas0000/.local/bin:/marconi/home/userexternal/vdas0000/bin)
./gen_ldc_version_info.py  > utils/ldc_version_info_.d
```
Can you let me know how to avoid this? I actually have sambamba in one of our HPC and it works fine however we are in a new HPC now where we have space and need to use sambamba for large number of bams we are generating and having issues in installing it in our new HPC. It will be great if you can suggest to fix this issue. Thanks

**Comment by lomereiter** [comment]
Can you run `ldmd2` from the command line? It could be that GLIBC is too old. 

Also you should have "ldc2-0.17.5-linux-x86_64/**lib**" in $LIBRARY_PATH

**Comment by vd4mmind** [comment]
I changed my $LIBRARY_PATH now
it is ```
echo $LIBRARY_PATH
/marconi/home/userexternal/vdas0000/marconi/home/userexternal/vdas0000/ldc2-0.17.5-linux-x86_64/lib
```
I realized I was putting wrong stuffs in my $LIBRARY_PATH however `ldmd2` is not running from command line.
```
ldmd2
-bash: ldmd2: command not found
```
so, in that case, what should I do? install `ldmd2` put it in both $PATH and $LIBRARY_PATH and then try to do `make` for proper installation of `sambamba`? Can you let me know if that is the way to be done?

**Comment by vd4mmind** [comment]
you may close this issue. The env variables were wrong. I am able to install the tool. thanks
