### ISSUE TITLE
Allow markdup to work with multiple files

### ISSUE THREAD

**Issue by lomereiter** [lomereiter/sambamba#71]

**Comment by buchhalt** [comment]
Hi Artem,
Any progress on this end? We would love to switch to sambamba for merging and marking of duplicates but we don't want to do it in two separate steps. We would highly appreciate if you could add this function!

**Comment by lomereiter** [comment]
Hi Ivo, this feature should be working in the new version, please give it a solid test!

**Comment by rernst** [comment]
Very interesting, I will try this out as well!

Op wo 5 aug. 2015 om 13:38 schreef Artem Tarasov <notifications@github.com>:

**Comment by buchhalt** [comment]
Hi Artem,

Thank you very much! We are still testing the results but the performance is great as always!

**Comment by rernst** [comment]
Works great, thanks for this new feature!
