### ISSUE TITLE
Receive input from stdin - sambamba pipes

### ISSUE THREAD

**Issue by afrendeiro** [lomereiter/sambamba#81]
I see there's a closed issue related https://github.com/lomereiter/sambamba/issues/27, and I'm not sure why it wasn't implemented.

It would be cool to pipe the tools as a way to reduce I/O:
`sambamba view -F "mapped" $SAMPLE | sambamba sort -`
 but currently it appears they can't read from stdin.

**Comment by pjotrp** [comment]
Fixed.

**Comment by crazyhottommy** [comment]
can you mix /dev/stdin and file name?

```bash
bowtie -q fastq -S | samtools view -Sb -F 4 - \
| samtools sort -m 2G -@ 5 -T tmp \
| sambamba markdup -r /dev/stdin my.out.bam

```

**Comment by lomereiter** [comment]
@crazyhottommy in general yes, but not with `markdup` as it requires two passes (the only tool that works in a single pass I know of is [samblaster](https://github.com/GregoryFaust/samblaster) which must be run before sort.

**Comment by crazyhottommy** [comment]
To make myself clear, I want to remove the duplicates, that's why I specify `-r`
samblaster should run after or before sort? 

```
bowtie -q fastq -S | samtools view -Sb - \
| samtools sort -m 2G -@ 10 -T temp \
| samtools view -h - | samblaster \
| samtools view -bS - > my_dup_rm.sorted.bam

```

Thanks!

**Comment by lomereiter** [comment]
It's run before sort, use same `-r` flag. Please follow the link above and read its documentation, it has examples as well.

**Comment by crazyhottommy** [comment]
Thank you! I just read that.

**Comment by yangyxt** [comment]
I'm not quite familiar with how OS handles /dev/stdin but I wonder whether using /dev/stdin would raise concerns when you run this command in parallel?
