### ISSUE TITLE
The -t switch always allocates an extra thread

### ISSUE THREAD

**Issue by pjotrp** [lomereiter/sambamba#94]
Can we limit cores to one using the -t 1 switch? Now sambamba always takes 2. I know, it takes 2 to tango ;)

**Comment by sambrightman** [comment]
As far as I'm aware there are 1 + 3*t threads currently when all worker threads are busy. Main thread,  t thread pool threads for reading the BAM, t worker threads and a producer thread for the pipe from each of those workers.

I don't think this is a bug: most of them will not be busy most of the time and if workers are fully utilised load average will be roughly equal to t. However, I find that worker threads are not fully utilised (see issue #237).
